// Package guest.v1 is the k3sm VM-pod guest contract: everything that crosses
// the host↔guest boundary for a `vm`-backend pod. It carries all three parts of
// that boundary in ONE home — the GuestAgent vsock gRPC service, the GuestSpec
// the guest init reads at boot, and the VMHostSpec the per-pod VM host process
// reads to build the machine — because they describe one boundary and splitting
// them across packages would only add import paths (there is deliberately no
// k3sm.io/apis/vm/v1).
//
// WHY THIS IS A VERSIONED WIRE CONTRACT even though both ends are built from
// k3sm.io/runtimed: the guest end ships inside the INITRAMFS, an independently
// released, sha256-pinned artifact acquired at install time — not a symbol
// linked into the daemon. A node can therefore run a daemon and an initramfs
// that were not built together, so the boundary is a wire contract in fact and
// is treated as one here.
//
// COMPAT POSTURE: compat is LOCKSTEP via the in-code initramfs sha256 pin. The
// supported configuration is exactly the daemon paired with the initramfs its
// own pin names; `--guest-artifacts-dir` (the dev-lab override) is UNSUPPORTED
// SKEW. Because "unsupported" must still be legible rather than silent stream
// corruption, GuestAgent.Health carries api_version + capabilities: a host that
// dials an agent speaking a different api_version rejects the pod with a stated
// reason instead of proceeding.
//
// Stability contract: as in runtime.proto — field numbers are STABLE and the
// surface is ADDITIVE-ONLY forever. Never renumber or repurpose a field; never
// reuse a reserved number/name. Every message keeps the file convention's
// `reserved 100 to 149;` headroom band. `buf breaking` (WIRE_JSON) enforces it
// against buf/baseline.binpb.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: guest/v1/guest.proto

package guestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "k3sm.io/apis/runtime/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuestAgent_Health_FullMethodName          = "/k3sm.guest.v1.GuestAgent/Health"
	GuestAgent_ContainerEvents_FullMethodName = "/k3sm.guest.v1.GuestAgent/ContainerEvents"
	GuestAgent_Exec_FullMethodName            = "/k3sm.guest.v1.GuestAgent/Exec"
	GuestAgent_Logs_FullMethodName            = "/k3sm.guest.v1.GuestAgent/Logs"
	GuestAgent_Stats_FullMethodName           = "/k3sm.guest.v1.GuestAgent/Stats"
	GuestAgent_Stop_FullMethodName            = "/k3sm.guest.v1.GuestAgent/Stop"
)

// GuestAgentClient is the client API for GuestAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GuestAgent is the in-guest agent (PID 1 of the micro-VM, shipped in the
// pinned initramfs). It is served over VSOCK on GuestSpec.agent_port and dialed
// by the per-pod VM host process, which proxies it to a runtimed-PRIVATE unix
// socket — never a path inside the pod dir, and never reachable from the pod
// itself.
//
// Single-pod guest. One VM hosts exactly one pod, so every RPC below is scoped
// to that pod implicitly. Requests still carry pod_id, and the agent MUST
// reject a pod_id that is not the pod it booted: the id is an assertion the
// caller reached the guest it meant to reach, not a selector over several.
// `container` is the real selector within the pod.
//
// Trust: everything the agent returns is guest-controlled data. The guest runs
// the workload, so a compromised workload can shape these responses. The host
// reads them with bounded reads and lets them affect nothing beyond that one
// pod's own status.
//
// RPC numbering note: gRPC method names (not numbers) are the wire identity, so
// there is no numeric range to reserve. This service is APPEND-ONLY — do not
// remove or rename a method.
type GuestAgentClient interface {
	// Health reports guest readiness, the DHCP-leased guest address, whether
	// Rosetta binfmt registration succeeded, and the agent's api_version /
	// capabilities. It is the pod's boot-deadline probe AND the single authority
	// on the guest's live address — the host does not re-derive the address from
	// the network attachment.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// ContainerEvents streams container lifecycle transitions (started / exited)
	// for the booted pod. It is the ONLY source of OOM truth for a vm pod: the
	// kill happens in the guest's cgroup, so the host's rusage sampler can never
	// observe it and must never synthesize it.
	ContainerEvents(ctx context.Context, in *ContainerEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContainerEvent], error)
	// Exec runs `kubectl exec` inside a guest container, reusing the runtime/v1
	// exec stream messages verbatim. In ExecRequest, pod_id MUST equal the pod
	// this guest booted (the agent rejects any other) and container selects
	// within it; the remaining fields keep their runtime/v1 meaning exactly.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.ExecRequest, v1.ExecResponse], error)
	// Logs streams a guest container's output, reusing the runtime/v1 log stream
	// messages verbatim. In GetLogsRequest, pod_id MUST equal the pod this guest
	// booted and container selects within it; follow / tail_lines / since_time /
	// timestamps / previous / limit_bytes keep their runtime/v1 meaning.
	Logs(ctx context.Context, in *v1.GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.LogEntry], error)
	// Stats returns a per-container resource sample read from the guest's cgroup2
	// hierarchy. It is answered ON DEMAND — the host asks when it needs a sample
	// and never runs a sampling ticker against a guest, because the vm path has
	// no OOM race to poll for (the hypervisor memory ceiling is enforced by the
	// VM, and OOM arrives as a ContainerEvent).
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Stop begins guest shutdown: SIGTERM to every container, then SIGKILL to
	// whatever is left after grace_seconds, then filesystem sync and poweroff.
	// The caller's grace budget must fit inside the daemon's own launchd exit
	// timeout; a larger grace is clamped by the host before it is sent.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type guestAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewGuestAgentClient(cc grpc.ClientConnInterface) GuestAgentClient {
	return &guestAgentClient{cc}
}

func (c *guestAgentClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) ContainerEvents(ctx context.Context, in *ContainerEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContainerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[0], GuestAgent_ContainerEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ContainerEventsRequest, ContainerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_ContainerEventsClient = grpc.ServerStreamingClient[ContainerEvent]

func (c *guestAgentClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.ExecRequest, v1.ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[1], GuestAgent_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.ExecRequest, v1.ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_ExecClient = grpc.BidiStreamingClient[v1.ExecRequest, v1.ExecResponse]

func (c *guestAgentClient) Logs(ctx context.Context, in *v1.GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[2], GuestAgent_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.GetLogsRequest, v1.LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_LogsClient = grpc.ServerStreamingClient[v1.LogEntry]

func (c *guestAgentClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestAgentServer is the server API for GuestAgent service.
// All implementations must embed UnimplementedGuestAgentServer
// for forward compatibility.
//
// GuestAgent is the in-guest agent (PID 1 of the micro-VM, shipped in the
// pinned initramfs). It is served over VSOCK on GuestSpec.agent_port and dialed
// by the per-pod VM host process, which proxies it to a runtimed-PRIVATE unix
// socket — never a path inside the pod dir, and never reachable from the pod
// itself.
//
// Single-pod guest. One VM hosts exactly one pod, so every RPC below is scoped
// to that pod implicitly. Requests still carry pod_id, and the agent MUST
// reject a pod_id that is not the pod it booted: the id is an assertion the
// caller reached the guest it meant to reach, not a selector over several.
// `container` is the real selector within the pod.
//
// Trust: everything the agent returns is guest-controlled data. The guest runs
// the workload, so a compromised workload can shape these responses. The host
// reads them with bounded reads and lets them affect nothing beyond that one
// pod's own status.
//
// RPC numbering note: gRPC method names (not numbers) are the wire identity, so
// there is no numeric range to reserve. This service is APPEND-ONLY — do not
// remove or rename a method.
type GuestAgentServer interface {
	// Health reports guest readiness, the DHCP-leased guest address, whether
	// Rosetta binfmt registration succeeded, and the agent's api_version /
	// capabilities. It is the pod's boot-deadline probe AND the single authority
	// on the guest's live address — the host does not re-derive the address from
	// the network attachment.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// ContainerEvents streams container lifecycle transitions (started / exited)
	// for the booted pod. It is the ONLY source of OOM truth for a vm pod: the
	// kill happens in the guest's cgroup, so the host's rusage sampler can never
	// observe it and must never synthesize it.
	ContainerEvents(*ContainerEventsRequest, grpc.ServerStreamingServer[ContainerEvent]) error
	// Exec runs `kubectl exec` inside a guest container, reusing the runtime/v1
	// exec stream messages verbatim. In ExecRequest, pod_id MUST equal the pod
	// this guest booted (the agent rejects any other) and container selects
	// within it; the remaining fields keep their runtime/v1 meaning exactly.
	Exec(grpc.BidiStreamingServer[v1.ExecRequest, v1.ExecResponse]) error
	// Logs streams a guest container's output, reusing the runtime/v1 log stream
	// messages verbatim. In GetLogsRequest, pod_id MUST equal the pod this guest
	// booted and container selects within it; follow / tail_lines / since_time /
	// timestamps / previous / limit_bytes keep their runtime/v1 meaning.
	Logs(*v1.GetLogsRequest, grpc.ServerStreamingServer[v1.LogEntry]) error
	// Stats returns a per-container resource sample read from the guest's cgroup2
	// hierarchy. It is answered ON DEMAND — the host asks when it needs a sample
	// and never runs a sampling ticker against a guest, because the vm path has
	// no OOM race to poll for (the hypervisor memory ceiling is enforced by the
	// VM, and OOM arrives as a ContainerEvent).
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Stop begins guest shutdown: SIGTERM to every container, then SIGKILL to
	// whatever is left after grace_seconds, then filesystem sync and poweroff.
	// The caller's grace budget must fit inside the daemon's own launchd exit
	// timeout; a larger grace is clamped by the host before it is sent.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedGuestAgentServer()
}

// UnimplementedGuestAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuestAgentServer struct{}

func (UnimplementedGuestAgentServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGuestAgentServer) ContainerEvents(*ContainerEventsRequest, grpc.ServerStreamingServer[ContainerEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ContainerEvents not implemented")
}
func (UnimplementedGuestAgentServer) Exec(grpc.BidiStreamingServer[v1.ExecRequest, v1.ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedGuestAgentServer) Logs(*v1.GetLogsRequest, grpc.ServerStreamingServer[v1.LogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedGuestAgentServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedGuestAgentServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedGuestAgentServer) mustEmbedUnimplementedGuestAgentServer() {}
func (UnimplementedGuestAgentServer) testEmbeddedByValue()                    {}

// UnsafeGuestAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuestAgentServer will
// result in compilation errors.
type UnsafeGuestAgentServer interface {
	mustEmbedUnimplementedGuestAgentServer()
}

func RegisterGuestAgentServer(s grpc.ServiceRegistrar, srv GuestAgentServer) {
	// If the following call pancis, it indicates UnimplementedGuestAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuestAgent_ServiceDesc, srv)
}

func _GuestAgent_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_ContainerEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContainerEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuestAgentServer).ContainerEvents(m, &grpc.GenericServerStream[ContainerEventsRequest, ContainerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_ContainerEventsServer = grpc.ServerStreamingServer[ContainerEvent]

func _GuestAgent_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GuestAgentServer).Exec(&grpc.GenericServerStream[v1.ExecRequest, v1.ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_ExecServer = grpc.BidiStreamingServer[v1.ExecRequest, v1.ExecResponse]

func _GuestAgent_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(v1.GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuestAgentServer).Logs(m, &grpc.GenericServerStream[v1.GetLogsRequest, v1.LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_LogsServer = grpc.ServerStreamingServer[v1.LogEntry]

func _GuestAgent_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuestAgent_ServiceDesc is the grpc.ServiceDesc for GuestAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuestAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k3sm.guest.v1.GuestAgent",
	HandlerType: (*GuestAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _GuestAgent_Health_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _GuestAgent_Stats_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _GuestAgent_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ContainerEvents",
			Handler:       _GuestAgent_ContainerEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _GuestAgent_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _GuestAgent_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "guest/v1/guest.proto",
}
