// Package guest.v1 is the k3sm VM-pod guest contract: everything that crosses
// the host↔guest boundary for a `vm`-backend pod. It carries all three parts of
// that boundary in ONE home — the GuestAgent vsock gRPC service, the GuestSpec
// the guest init reads at boot, and the VMHostSpec the per-pod VM host process
// reads to build the machine — because they describe one boundary and splitting
// them across packages would only add import paths (there is deliberately no
// k3sm.io/apis/vm/v1).
//
// WHY THIS IS A VERSIONED WIRE CONTRACT even though both ends are built from
// k3sm.io/runtimed: the guest end ships inside the INITRAMFS, an independently
// released, sha256-pinned artifact acquired at install time — not a symbol
// linked into the daemon. A node can therefore run a daemon and an initramfs
// that were not built together, so the boundary is a wire contract in fact and
// is treated as one here.
//
// COMPAT POSTURE: compat is LOCKSTEP via the in-code initramfs sha256 pin. The
// supported configuration is exactly the daemon paired with the initramfs its
// own pin names; `--guest-artifacts-dir` (the dev-lab override) is UNSUPPORTED
// SKEW. Because "unsupported" must still be legible rather than silent stream
// corruption, GuestAgent.Health carries api_version + capabilities: a host that
// dials an agent speaking a different api_version rejects the pod with a stated
// reason instead of proceeding.
//
// Stability contract: as in runtime.proto — field numbers are STABLE and the
// surface is ADDITIVE-ONLY forever. Never renumber or repurpose a field; never
// reuse a reserved number/name. Every message keeps the file convention's
// `reserved 100 to 149;` headroom band. `buf breaking` (WIRE_JSON) enforces it
// against buf/baseline.binpb.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: guest/v1/guest.proto

package guestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "k3sm.io/apis/runtime/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GuestMountKind is how a GuestMount is realized in the guest.
type GuestMountKind int32

const (
	GuestMountKind_GUEST_MOUNT_KIND_UNSPECIFIED GuestMountKind = 0
	// VIRTIOFS mounts a host-attached virtiofs share, selected by its device tag.
	GuestMountKind_GUEST_MOUNT_KIND_VIRTIOFS GuestMountKind = 1
	// TMPFS mounts guest RAM (an emptyDir with medium Memory, and the writable
	// upper of a rootfs overlay). It never crosses virtiofs.
	GuestMountKind_GUEST_MOUNT_KIND_TMPFS GuestMountKind = 2
	// BIND re-exposes an already-mounted guest path at a second target, which is
	// how per-container /etc files and per-container subpaths are composed.
	GuestMountKind_GUEST_MOUNT_KIND_BIND GuestMountKind = 3
)

// Enum value maps for GuestMountKind.
var (
	GuestMountKind_name = map[int32]string{
		0: "GUEST_MOUNT_KIND_UNSPECIFIED",
		1: "GUEST_MOUNT_KIND_VIRTIOFS",
		2: "GUEST_MOUNT_KIND_TMPFS",
		3: "GUEST_MOUNT_KIND_BIND",
	}
	GuestMountKind_value = map[string]int32{
		"GUEST_MOUNT_KIND_UNSPECIFIED": 0,
		"GUEST_MOUNT_KIND_VIRTIOFS":    1,
		"GUEST_MOUNT_KIND_TMPFS":       2,
		"GUEST_MOUNT_KIND_BIND":        3,
	}
)

func (x GuestMountKind) Enum() *GuestMountKind {
	p := new(GuestMountKind)
	*p = x
	return p
}

func (x GuestMountKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuestMountKind) Descriptor() protoreflect.EnumDescriptor {
	return file_guest_v1_guest_proto_enumTypes[0].Descriptor()
}

func (GuestMountKind) Type() protoreflect.EnumType {
	return &file_guest_v1_guest_proto_enumTypes[0]
}

func (x GuestMountKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuestMountKind.Descriptor instead.
func (GuestMountKind) EnumDescriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{0}
}

// HealthRequest is empty (the guest hosts exactly one pod, so there is nothing
// to select). Reserved for future filters.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{0}
}

// HealthResponse is the guest's readiness + identity report.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ready is true once the boot sequence has completed far enough to accept the
	// other RPCs (filesystems mounted, spec read, network configured).
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// guest_ip is the address the guest's DHCP client leased on eth0, in dotted
	// form; empty until the lease is held. This field is the single live-address
	// authority for a vm pod: the host consumes what the agent reports here and
	// never re-derives the address from the network attachment. It feeds
	// k3sm.runtime.v1 PodStatus.guest_transport_address, which is how it crosses
	// to the host's dial paths.
	//
	// It is the pod's live transport address — what the host dials to reach this
	// guest (Service-proxy backend dials, probes, port-forward, and later policy
	// attribution). It is not the pod's published status IP: that stays
	// k3sm.runtime.v1 PodStatus.pod_ip / pod_ips, the podCIDR /32 the host
	// assigns and publishes to EndpointSlice, DNS, and the downward API. The two
	// are different addresses on different segments and neither substitutes for
	// the other.
	//
	// It may change across a guest restart, because it is a lease. A lease change
	// is therefore observable as a change in this field, and a consumer re-reads
	// it rather than caching it as a stable identifier.
	GuestIp string `protobuf:"bytes,2,opt,name=guest_ip,json=guestIp,proto3" json:"guest_ip,omitempty"`
	// rosetta_registered is true when the guest completed Rosetta binfmt_misc
	// registration, so linux/amd64 payloads in this pod will execute. It is
	// false — not an error — on a guest that was booted without Rosetta.
	RosettaRegistered bool `protobuf:"varint,3,opt,name=rosetta_registered,json=rosettaRegistered,proto3" json:"rosetta_registered,omitempty"`
	// api_version is the guest/v1 contract version this agent speaks. Compat is
	// lockstep via the initramfs sha256 pin, so a mismatch means the operator is
	// running unsupported skew (a dev-lab --guest-artifacts-dir pairing): the
	// host MUST fail the pod with that stated reason rather than continue and
	// discover the mismatch as malformed streams.
	ApiVersion string `protobuf:"bytes,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// capabilities are optional feature tokens the agent advertises. It exists so
	// a capability can be negotiated WITHOUT an api_version bump for changes that
	// are genuinely additive; an unknown token is ignored by the host.
	Capabilities  []string `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_guest_v1_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetGuestIp() string {
	if x != nil {
		return x.GuestIp
	}
	return ""
}

func (x *HealthResponse) GetRosettaRegistered() bool {
	if x != nil {
		return x.RosettaRegistered
	}
	return false
}

func (x *HealthResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *HealthResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ContainerEventsRequest subscribes to the booted pod's lifecycle stream.
type ContainerEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pod_id must equal the pod this guest booted; the agent rejects any other.
	PodId         string `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEventsRequest) Reset() {
	*x = ContainerEventsRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEventsRequest) ProtoMessage() {}

func (x *ContainerEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEventsRequest.ProtoReflect.Descriptor instead.
func (*ContainerEventsRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerEventsRequest) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

// ContainerEvent is one container lifecycle transition. Exactly one of started
// or exited is set — the optional-message union, matching the runtime/v1
// ContainerState precedent rather than a oneof.
type ContainerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container is the container name within the pod.
	Container string `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	// timestamp is when the guest observed the transition.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// started and exited are the event union: exactly one is set.
	Started       *ContainerStarted `protobuf:"bytes,3,opt,name=started,proto3" json:"started,omitempty"`
	Exited        *ContainerExited  `protobuf:"bytes,4,opt,name=exited,proto3" json:"exited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEvent) Reset() {
	*x = ContainerEvent{}
	mi := &file_guest_v1_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEvent) ProtoMessage() {}

func (x *ContainerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEvent.ProtoReflect.Descriptor instead.
func (*ContainerEvent) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerEvent) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ContainerEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ContainerEvent) GetStarted() *ContainerStarted {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *ContainerEvent) GetExited() *ContainerExited {
	if x != nil {
		return x.Exited
	}
	return nil
}

// ContainerStarted reports that a container's process was spawned in the guest.
type ContainerStarted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pid is the process id INSIDE the guest, useful only for guest-side
	// correlation — it means nothing to the host process table.
	Pid           int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStarted) Reset() {
	*x = ContainerStarted{}
	mi := &file_guest_v1_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStarted) ProtoMessage() {}

func (x *ContainerStarted) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStarted.ProtoReflect.Descriptor instead.
func (*ContainerStarted) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerStarted) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// ContainerExited reports a container's terminal outcome.
type ContainerExited struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code is the process exit status (0..255) when it exited normally.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// signal is the terminating signal number when the process was killed, else
	// 0. It is the guest's signal number, so it is Linux's numbering.
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// oom_killed is true when the guest kernel's cgroup OOM killer ended the
	// process. This is the ONLY way a vm pod is ever marked OOMKilled: the host
	// cannot see a guest cgroup event, so it never derives OOMKilled from its own
	// sampling for a vm pod.
	OomKilled     bool `protobuf:"varint,3,opt,name=oom_killed,json=oomKilled,proto3" json:"oom_killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExited) Reset() {
	*x = ContainerExited{}
	mi := &file_guest_v1_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExited) ProtoMessage() {}

func (x *ContainerExited) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExited.ProtoReflect.Descriptor instead.
func (*ContainerExited) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerExited) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *ContainerExited) GetOomKilled() bool {
	if x != nil {
		return x.OomKilled
	}
	return false
}

// StatsRequest asks for a resource sample of the booted pod.
type StatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pod_id must equal the pod this guest booted; the agent rejects any other.
	PodId         string `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{6}
}

func (x *StatsRequest) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

// StatsResponse carries one on-demand sample per container.
type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp is when the guest took the sample.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// containers are the per-container samples, one per running container. A
	// container the agent could not read is OMITTED rather than reported as
	// zeros: a zero sample is indistinguishable from an idle container, so
	// absence is the only honest encoding of "unknown".
	Containers    []*GuestContainerStats `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_guest_v1_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{7}
}

func (x *StatsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StatsResponse) GetContainers() []*GuestContainerStats {
	if x != nil {
		return x.Containers
	}
	return nil
}

// GuestContainerStats is one container's cgroup2 sample. It is deliberately NOT
// the runtime/v1 ContainerStats: those fields are sourced from Darwin
// proc_pid_rusage and carry that provenance in their names and semantics, while
// these two come from the guest's cgroup2 files. The host maps these onto the
// kubelet Summary shape at the boundary, so a reader can always tell which
// kernel produced a number.
type GuestContainerStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container is the container name within the pod.
	Container string `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	// cpu_usage_usec is cumulative CPU time in MICROSECONDS, read from the
	// cgroup2 cpu.stat `usage_usec` counter.
	CpuUsageUsec uint64 `protobuf:"varint,2,opt,name=cpu_usage_usec,json=cpuUsageUsec,proto3" json:"cpu_usage_usec,omitempty"`
	// memory_working_set_bytes is the working set, computed as
	// memory.current − memory.stat inactive_file — the cgroup2 definition kubelet
	// uses, not memory.current alone (page cache would otherwise be charged as
	// live memory).
	MemoryWorkingSetBytes uint64 `protobuf:"varint,3,opt,name=memory_working_set_bytes,json=memoryWorkingSetBytes,proto3" json:"memory_working_set_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GuestContainerStats) Reset() {
	*x = GuestContainerStats{}
	mi := &file_guest_v1_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestContainerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestContainerStats) ProtoMessage() {}

func (x *GuestContainerStats) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestContainerStats.ProtoReflect.Descriptor instead.
func (*GuestContainerStats) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{8}
}

func (x *GuestContainerStats) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *GuestContainerStats) GetCpuUsageUsec() uint64 {
	if x != nil {
		return x.CpuUsageUsec
	}
	return 0
}

func (x *GuestContainerStats) GetMemoryWorkingSetBytes() uint64 {
	if x != nil {
		return x.MemoryWorkingSetBytes
	}
	return 0
}

// StopRequest asks the guest to shut down.
type StopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// grace_seconds is the budget for graceful termination before SIGKILL. The
	// host clamps it to fit inside the daemon's launchd exit timeout before
	// sending, so the guest can treat it as already-budgeted.
	GraceSeconds  int32 `protobuf:"varint,1,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_guest_v1_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{9}
}

func (x *StopRequest) GetGraceSeconds() int32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

// StopResponse is empty: shutdown is acknowledged by the call returning, and
// the guest powers off immediately after. Reserved for future detail.
type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_guest_v1_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{10}
}

// GuestSpec is everything the guest init needs to realize one pod. It is
// produced host-side (all Kubernetes-level resolution — env, image config
// merge, user resolution inputs — has already happened) and consumed by the
// guest exactly as given.
type GuestSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hostname is the pod hostname set in the guest and bound into every
	// container's /etc/hostname.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// resolv_conf is the DNS configuration bound into every container's
	// /etc/resolv.conf. It is carried STRUCTURED rather than as rendered file
	// bytes so the guest can render it musl-safely (alpine's resolver ignores
	// `options ndots`, so the search list must not depend on it).
	ResolvConf *ResolvConf `protobuf:"bytes,2,opt,name=resolv_conf,json=resolvConf,proto3" json:"resolv_conf,omitempty"`
	// containers are the pod's containers in start order: init containers (init
	// = true) first and sequentially, then the main containers.
	Containers []*GuestContainer `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	// mounts are the pod-level mounts the guest sets up before any container
	// starts (virtiofs shares, tmpfs, binds).
	Mounts []*GuestMount `protobuf:"bytes,4,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// rosetta is true when the VM was created with the Rosetta share attached, so
	// the guest should register the linux/amd64 binfmt_misc interpreter.
	Rosetta bool `protobuf:"varint,5,opt,name=rosetta,proto3" json:"rosetta,omitempty"`
	// fs_group is the pod's fsGroup, applied via idmapped mounts (never a
	// recursive chown). 0 means unset.
	FsGroup int64 `protobuf:"varint,6,opt,name=fs_group,json=fsGroup,proto3" json:"fs_group,omitempty"`
	// agent_port is the VSOCK port the agent listens on. It MUST equal
	// VMHostSpec.agent_vsock_port — the two specs are written by the same host
	// and a disagreement makes the guest unreachable.
	AgentPort     uint32 `protobuf:"varint,7,opt,name=agent_port,json=agentPort,proto3" json:"agent_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestSpec) Reset() {
	*x = GuestSpec{}
	mi := &file_guest_v1_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestSpec) ProtoMessage() {}

func (x *GuestSpec) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestSpec.ProtoReflect.Descriptor instead.
func (*GuestSpec) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{11}
}

func (x *GuestSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GuestSpec) GetResolvConf() *ResolvConf {
	if x != nil {
		return x.ResolvConf
	}
	return nil
}

func (x *GuestSpec) GetContainers() []*GuestContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *GuestSpec) GetMounts() []*GuestMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *GuestSpec) GetRosetta() bool {
	if x != nil {
		return x.Rosetta
	}
	return false
}

func (x *GuestSpec) GetFsGroup() int64 {
	if x != nil {
		return x.FsGroup
	}
	return 0
}

func (x *GuestSpec) GetAgentPort() uint32 {
	if x != nil {
		return x.AgentPort
	}
	return 0
}

// ResolvConf is the guest's DNS configuration, rendered into
// /etc/resolv.conf by the guest init. Mirrors the three resolv.conf directives
// k3sm sets; ordering within each list is significant and preserved.
type ResolvConf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nameservers are resolver addresses in query order.
	Nameservers []string `protobuf:"bytes,1,rep,name=nameservers,proto3" json:"nameservers,omitempty"`
	// searches is the search list, in order.
	Searches []string `protobuf:"bytes,2,rep,name=searches,proto3" json:"searches,omitempty"`
	// options are resolver options (e.g. "ndots:5"). A musl guest ignores some of
	// these, which is why the search list must stand on its own.
	Options       []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvConf) Reset() {
	*x = ResolvConf{}
	mi := &file_guest_v1_guest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvConf) ProtoMessage() {}

func (x *ResolvConf) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvConf.ProtoReflect.Descriptor instead.
func (*ResolvConf) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{12}
}

func (x *ResolvConf) GetNameservers() []string {
	if x != nil {
		return x.Nameservers
	}
	return nil
}

func (x *ResolvConf) GetSearches() []string {
	if x != nil {
		return x.Searches
	}
	return nil
}

func (x *ResolvConf) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// GuestContainer is one container to run inside the guest.
type GuestContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the container name, unique within the pod. It is the selector
	// Exec / Logs / Stats and ContainerEvent use.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// rootfs_tag names the virtiofs share carrying this container's rootfs lower
	// layer. The guest composes writability as an overlay (that share is
	// read-only at the VZ device); the tag is the only rootfs identity that
	// crosses the boundary — no host path does.
	RootfsTag string `protobuf:"bytes,2,opt,name=rootfs_tag,json=rootfsTag,proto3" json:"rootfs_tag,omitempty"`
	// command and args form argv: argv = command + args. They are already merged
	// host-side against the image config (Entrypoint/Cmd) per the Kubernetes
	// four-quadrant rule — the guest performs no further merge and consults no
	// image config of its own.
	Command []string `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	// env are fully resolved "KEY=VALUE" entries. Every Kubernetes indirection
	// (valueFrom, envFrom, $(VAR) expansion) is resolved host-side, so the guest
	// needs no cluster access to start a container.
	Env []string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	// working_dir is the process working directory inside the container rootfs;
	// empty means the image config's WorkingDir as already merged host-side.
	WorkingDir string `protobuf:"bytes,6,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// tty requests a pseudo-terminal for the container's process.
	Tty bool `protobuf:"varint,7,opt,name=tty,proto3" json:"tty,omitempty"`
	// stdin keeps stdin open for the container's process.
	Stdin bool `protobuf:"varint,8,opt,name=stdin,proto3" json:"stdin,omitempty"`
	// uid and gid are the resolved numeric ids the process runs as. Resolution of
	// a non-numeric image USER against the rootfs's /etc/passwd happens IN THE
	// GUEST at execution time (the host does not read a pod-controlled passwd
	// file); when the host already knows the numeric answer it stamps it here.
	Uid int64 `protobuf:"varint,9,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid int64 `protobuf:"varint,10,opt,name=gid,proto3" json:"gid,omitempty"`
	// supplemental_gids are the additional groups, including the pod fsGroup.
	SupplementalGids []int64 `protobuf:"varint,11,rep,packed,name=supplemental_gids,json=supplementalGids,proto3" json:"supplemental_gids,omitempty"`
	// init marks an init container: it runs to completion, in list order, before
	// any main container starts.
	Init          bool `protobuf:"varint,12,opt,name=init,proto3" json:"init,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestContainer) Reset() {
	*x = GuestContainer{}
	mi := &file_guest_v1_guest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestContainer) ProtoMessage() {}

func (x *GuestContainer) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestContainer.ProtoReflect.Descriptor instead.
func (*GuestContainer) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{13}
}

func (x *GuestContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuestContainer) GetRootfsTag() string {
	if x != nil {
		return x.RootfsTag
	}
	return ""
}

func (x *GuestContainer) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *GuestContainer) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *GuestContainer) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *GuestContainer) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *GuestContainer) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *GuestContainer) GetStdin() bool {
	if x != nil {
		return x.Stdin
	}
	return false
}

func (x *GuestContainer) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GuestContainer) GetGid() int64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GuestContainer) GetSupplementalGids() []int64 {
	if x != nil {
		return x.SupplementalGids
	}
	return nil
}

func (x *GuestContainer) GetInit() bool {
	if x != nil {
		return x.Init
	}
	return false
}

// GuestMount is one mount the guest init performs.
type GuestMount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tag_or_source is the virtiofs device TAG for VIRTIOFS, the source path for
	// BIND, and empty for TMPFS. It is never a host path: the host path a share
	// was built from stays in VMHostSpec and never enters the guest.
	TagOrSource string `protobuf:"bytes,1,opt,name=tag_or_source,json=tagOrSource,proto3" json:"tag_or_source,omitempty"`
	// target is the absolute mount point inside the guest.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// kind selects how the mount is realized.
	Kind GuestMountKind `protobuf:"varint,3,opt,name=kind,proto3,enum=k3sm.guest.v1.GuestMountKind" json:"kind,omitempty"`
	// read_only mounts without write access. For a virtiofs share this MIRRORS a
	// read-only setting already applied at the VZ device — the guest-side flag is
	// defence in depth, never the only enforcement.
	ReadOnly bool `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// size_limit_bytes bounds a TMPFS mount; 0 means unbounded. Bounding the
	// overlay upper matters: an unbounded upper turns a runaway write into a
	// guest OOM that is then misattributed to the workload's memory use, while a
	// bounded one fails as ENOSPC where it happened.
	SizeLimitBytes int64 `protobuf:"varint,5,opt,name=size_limit_bytes,json=sizeLimitBytes,proto3" json:"size_limit_bytes,omitempty"`
	// idmap requests an idmapped mount (Linux MOUNT_ATTR_IDMAP) so files owned by
	// the host-side owner appear as the container's effective uid/fsGroup. This
	// is how fsGroup is honored with ZERO recursive chown on either side.
	Idmap         bool `protobuf:"varint,6,opt,name=idmap,proto3" json:"idmap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestMount) Reset() {
	*x = GuestMount{}
	mi := &file_guest_v1_guest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestMount) ProtoMessage() {}

func (x *GuestMount) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestMount.ProtoReflect.Descriptor instead.
func (*GuestMount) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{14}
}

func (x *GuestMount) GetTagOrSource() string {
	if x != nil {
		return x.TagOrSource
	}
	return ""
}

func (x *GuestMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GuestMount) GetKind() GuestMountKind {
	if x != nil {
		return x.Kind
	}
	return GuestMountKind_GUEST_MOUNT_KIND_UNSPECIFIED
}

func (x *GuestMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *GuestMount) GetSizeLimitBytes() int64 {
	if x != nil {
		return x.SizeLimitBytes
	}
	return 0
}

func (x *GuestMount) GetIdmap() bool {
	if x != nil {
		return x.Idmap
	}
	return false
}

// VMHostSpec is the whole description of one pod's virtual machine. It is
// deliberately mechanical: every policy decision (which platform, which shares,
// how much memory) is already made by the time this is written, so the VM host
// process is a translator and never a decision-maker.
type VMHostSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pod_id is the kube Pod UID this VM hosts. It also seeds the deterministic
	// locally-administered MAC when mac_address is empty.
	PodId string `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	// vcpus is the virtual CPU count.
	Vcpus uint32 `protobuf:"varint,2,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	// memory_bytes is the guest RAM size. It is the HYPERVISOR-ENFORCED ceiling
	// for the pod, which is why the vm path needs no host-side memory sampling to
	// enforce a limit.
	MemoryBytes int64 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// kernel_path and initramfs_path are host paths to the pinned guest
	// artifacts. Their sha256 digests are pinned IN CODE and verified before use;
	// these fields carry only where the verified artifacts live.
	KernelPath    string `protobuf:"bytes,4,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	InitramfsPath string `protobuf:"bytes,5,opt,name=initramfs_path,json=initramfsPath,proto3" json:"initramfs_path,omitempty"`
	// cmdline is the kernel command line.
	Cmdline string `protobuf:"bytes,6,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	// shares are the virtiofs devices attached to the machine.
	Shares []*VMShare `protobuf:"bytes,7,rep,name=shares,proto3" json:"shares,omitempty"`
	// rosetta attaches the Rosetta share so the guest can register the
	// linux/amd64 interpreter. It must agree with GuestSpec.rosetta.
	Rosetta bool `protobuf:"varint,8,opt,name=rosetta,proto3" json:"rosetta,omitempty"`
	// agent_vsock_port is the VSOCK port the host dials to reach the guest agent.
	// It MUST equal GuestSpec.agent_port.
	AgentVsockPort uint32 `protobuf:"varint,9,opt,name=agent_vsock_port,json=agentVsockPort,proto3" json:"agent_vsock_port,omitempty"`
	// mac_address is the guest NIC's MAC. Empty means derive it deterministically
	// from pod_id, which is what keeps a DHCP lease stable across a VM restart of
	// the same pod.
	MacAddress    string `protobuf:"bytes,10,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMHostSpec) Reset() {
	*x = VMHostSpec{}
	mi := &file_guest_v1_guest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMHostSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMHostSpec) ProtoMessage() {}

func (x *VMHostSpec) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMHostSpec.ProtoReflect.Descriptor instead.
func (*VMHostSpec) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{15}
}

func (x *VMHostSpec) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *VMHostSpec) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VMHostSpec) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VMHostSpec) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

func (x *VMHostSpec) GetInitramfsPath() string {
	if x != nil {
		return x.InitramfsPath
	}
	return ""
}

func (x *VMHostSpec) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *VMHostSpec) GetShares() []*VMShare {
	if x != nil {
		return x.Shares
	}
	return nil
}

func (x *VMHostSpec) GetRosetta() bool {
	if x != nil {
		return x.Rosetta
	}
	return false
}

func (x *VMHostSpec) GetAgentVsockPort() uint32 {
	if x != nil {
		return x.AgentVsockPort
	}
	return 0
}

func (x *VMHostSpec) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

// VMShare is one virtiofs device attached to the machine.
type VMShare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tag is the device tag the guest mounts by. It is the ONLY name the guest
	// learns; host_path never crosses the boundary.
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// host_path is the host directory exported by this share. Every share root
	// lives inside the owning pod's own directory tree (or a bound claim's
	// configured data dir), and the set is pairwise disjoint — no share is an
	// ancestor of another.
	HostPath string `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	// read_only exports the share without write access AT THE VZ DEVICE, which is
	// the enforcement point. A guest-side read_only flag mirrors it but cannot
	// substitute for it.
	ReadOnly      bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMShare) Reset() {
	*x = VMShare{}
	mi := &file_guest_v1_guest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMShare) ProtoMessage() {}

func (x *VMShare) ProtoReflect() protoreflect.Message {
	mi := &file_guest_v1_guest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMShare.ProtoReflect.Descriptor instead.
func (*VMShare) Descriptor() ([]byte, []int) {
	return file_guest_v1_guest_proto_rawDescGZIP(), []int{16}
}

func (x *VMShare) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *VMShare) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *VMShare) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

var File_guest_v1_guest_proto protoreflect.FileDescriptor

const file_guest_v1_guest_proto_rawDesc = "" +
	"\n" +
	"\x14guest/v1/guest.proto\x12\rk3sm.guest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18runtime/v1/runtime.proto\"\x0f\n" +
	"\rHealthRequest\"\xbc\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x19\n" +
	"\bguest_ip\x18\x02 \x01(\tR\aguestIp\x12-\n" +
	"\x12rosetta_registered\x18\x03 \x01(\bR\x11rosettaRegistered\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\tR\n" +
	"apiVersion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilitiesJ\x05\bd\x10\x96\x01\"6\n" +
	"\x16ContainerEventsRequest\x12\x15\n" +
	"\x06pod_id\x18\x01 \x01(\tR\x05podIdJ\x05\bd\x10\x96\x01\"\xe2\x01\n" +
	"\x0eContainerEvent\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\astarted\x18\x03 \x01(\v2\x1f.k3sm.guest.v1.ContainerStartedR\astarted\x126\n" +
	"\x06exited\x18\x04 \x01(\v2\x1e.k3sm.guest.v1.ContainerExitedR\x06exitedJ\x05\bd\x10\x96\x01\"+\n" +
	"\x10ContainerStarted\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pidJ\x05\bd\x10\x96\x01\"l\n" +
	"\x0fContainerExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\x12\x1d\n" +
	"\n" +
	"oom_killed\x18\x03 \x01(\bR\toomKilledJ\x05\bd\x10\x96\x01\",\n" +
	"\fStatsRequest\x12\x15\n" +
	"\x06pod_id\x18\x01 \x01(\tR\x05podIdJ\x05\bd\x10\x96\x01\"\x94\x01\n" +
	"\rStatsResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\".k3sm.guest.v1.GuestContainerStatsR\n" +
	"containersJ\x05\bd\x10\x96\x01\"\x99\x01\n" +
	"\x13GuestContainerStats\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12$\n" +
	"\x0ecpu_usage_usec\x18\x02 \x01(\x04R\fcpuUsageUsec\x127\n" +
	"\x18memory_working_set_bytes\x18\x03 \x01(\x04R\x15memoryWorkingSetBytesJ\x05\bd\x10\x96\x01\"9\n" +
	"\vStopRequest\x12#\n" +
	"\rgrace_seconds\x18\x01 \x01(\x05R\fgraceSecondsJ\x05\bd\x10\x96\x01\"\x15\n" +
	"\fStopResponseJ\x05\bd\x10\x96\x01\"\xb0\x02\n" +
	"\tGuestSpec\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12:\n" +
	"\vresolv_conf\x18\x02 \x01(\v2\x19.k3sm.guest.v1.ResolvConfR\n" +
	"resolvConf\x12=\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2\x1d.k3sm.guest.v1.GuestContainerR\n" +
	"containers\x121\n" +
	"\x06mounts\x18\x04 \x03(\v2\x19.k3sm.guest.v1.GuestMountR\x06mounts\x12\x18\n" +
	"\arosetta\x18\x05 \x01(\bR\arosetta\x12\x19\n" +
	"\bfs_group\x18\x06 \x01(\x03R\afsGroup\x12\x1d\n" +
	"\n" +
	"agent_port\x18\a \x01(\rR\tagentPortJ\x05\bd\x10\x96\x01\"k\n" +
	"\n" +
	"ResolvConf\x12 \n" +
	"\vnameservers\x18\x01 \x03(\tR\vnameservers\x12\x1a\n" +
	"\bsearches\x18\x02 \x03(\tR\bsearches\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptionsJ\x05\bd\x10\x96\x01\"\xb8\x02\n" +
	"\x0eGuestContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"rootfs_tag\x18\x02 \x01(\tR\trootfsTag\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x10\n" +
	"\x03env\x18\x05 \x03(\tR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x06 \x01(\tR\n" +
	"workingDir\x12\x10\n" +
	"\x03tty\x18\a \x01(\bR\x03tty\x12\x14\n" +
	"\x05stdin\x18\b \x01(\bR\x05stdin\x12\x10\n" +
	"\x03uid\x18\t \x01(\x03R\x03uid\x12\x10\n" +
	"\x03gid\x18\n" +
	" \x01(\x03R\x03gid\x12+\n" +
	"\x11supplemental_gids\x18\v \x03(\x03R\x10supplementalGids\x12\x12\n" +
	"\x04init\x18\f \x01(\bR\x04initJ\x05\bd\x10\x96\x01\"\xdf\x01\n" +
	"\n" +
	"GuestMount\x12\"\n" +
	"\rtag_or_source\x18\x01 \x01(\tR\vtagOrSource\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x121\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1d.k3sm.guest.v1.GuestMountKindR\x04kind\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12(\n" +
	"\x10size_limit_bytes\x18\x05 \x01(\x03R\x0esizeLimitBytes\x12\x14\n" +
	"\x05idmap\x18\x06 \x01(\bR\x05idmapJ\x05\bd\x10\x96\x01\"\xda\x02\n" +
	"\n" +
	"VMHostSpec\x12\x15\n" +
	"\x06pod_id\x18\x01 \x01(\tR\x05podId\x12\x14\n" +
	"\x05vcpus\x18\x02 \x01(\rR\x05vcpus\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x12\x1f\n" +
	"\vkernel_path\x18\x04 \x01(\tR\n" +
	"kernelPath\x12%\n" +
	"\x0einitramfs_path\x18\x05 \x01(\tR\rinitramfsPath\x12\x18\n" +
	"\acmdline\x18\x06 \x01(\tR\acmdline\x12.\n" +
	"\x06shares\x18\a \x03(\v2\x16.k3sm.guest.v1.VMShareR\x06shares\x12\x18\n" +
	"\arosetta\x18\b \x01(\bR\arosetta\x12(\n" +
	"\x10agent_vsock_port\x18\t \x01(\rR\x0eagentVsockPort\x12\x1f\n" +
	"\vmac_address\x18\n" +
	" \x01(\tR\n" +
	"macAddressJ\x05\bd\x10\x96\x01\"\\\n" +
	"\aVMShare\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1b\n" +
	"\thost_path\x18\x02 \x01(\tR\bhostPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnlyJ\x05\bd\x10\x96\x01*\x88\x01\n" +
	"\x0eGuestMountKind\x12 \n" +
	"\x1cGUEST_MOUNT_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GUEST_MOUNT_KIND_VIRTIOFS\x10\x01\x12\x1a\n" +
	"\x16GUEST_MOUNT_KIND_TMPFS\x10\x02\x12\x19\n" +
	"\x15GUEST_MOUNT_KIND_BIND\x10\x032\x91\x04\n" +
	"\n" +
	"GuestAgent\x12E\n" +
	"\x06Health\x12\x1c.k3sm.guest.v1.HealthRequest\x1a\x1d.k3sm.guest.v1.HealthResponse\x12Y\n" +
	"\x0fContainerEvents\x12%.k3sm.guest.v1.ContainerEventsRequest\x1a\x1d.k3sm.guest.v1.ContainerEvent0\x01\x12G\n" +
	"\x04Exec\x12\x1c.k3sm.runtime.v1.ExecRequest\x1a\x1d.k3sm.runtime.v1.ExecResponse(\x010\x01\x12D\n" +
	"\x04Logs\x12\x1f.k3sm.runtime.v1.GetLogsRequest\x1a\x19.k3sm.runtime.v1.LogEntry0\x01\x12B\n" +
	"\x05Stats\x12\x1b.k3sm.guest.v1.StatsRequest\x1a\x1c.k3sm.guest.v1.StatsResponse\x12?\n" +
	"\x04Stop\x12\x1a.k3sm.guest.v1.StopRequest\x1a\x1b.k3sm.guest.v1.StopResponse\x12M\n" +
	"\x06Attach\x12\x1e.k3sm.runtime.v1.AttachRequest\x1a\x1f.k3sm.runtime.v1.AttachResponse(\x010\x01B\x94\x01\n" +
	"\x11com.k3sm.guest.v1B\n" +
	"GuestProtoP\x01Z\x1dk3sm.io/apis/guest/v1;guestv1\xa2\x02\x03KGX\xaa\x02\rK3sm.Guest.V1\xca\x02\rK3sm\\Guest\\V1\xe2\x02\x19K3sm\\Guest\\V1\\GPBMetadata\xea\x02\x0fK3sm::Guest::V1b\x06proto3"

var (
	file_guest_v1_guest_proto_rawDescOnce sync.Once
	file_guest_v1_guest_proto_rawDescData []byte
)

func file_guest_v1_guest_proto_rawDescGZIP() []byte {
	file_guest_v1_guest_proto_rawDescOnce.Do(func() {
		file_guest_v1_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guest_v1_guest_proto_rawDesc), len(file_guest_v1_guest_proto_rawDesc)))
	})
	return file_guest_v1_guest_proto_rawDescData
}

var file_guest_v1_guest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_guest_v1_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_guest_v1_guest_proto_goTypes = []any{
	(GuestMountKind)(0),            // 0: k3sm.guest.v1.GuestMountKind
	(*HealthRequest)(nil),          // 1: k3sm.guest.v1.HealthRequest
	(*HealthResponse)(nil),         // 2: k3sm.guest.v1.HealthResponse
	(*ContainerEventsRequest)(nil), // 3: k3sm.guest.v1.ContainerEventsRequest
	(*ContainerEvent)(nil),         // 4: k3sm.guest.v1.ContainerEvent
	(*ContainerStarted)(nil),       // 5: k3sm.guest.v1.ContainerStarted
	(*ContainerExited)(nil),        // 6: k3sm.guest.v1.ContainerExited
	(*StatsRequest)(nil),           // 7: k3sm.guest.v1.StatsRequest
	(*StatsResponse)(nil),          // 8: k3sm.guest.v1.StatsResponse
	(*GuestContainerStats)(nil),    // 9: k3sm.guest.v1.GuestContainerStats
	(*StopRequest)(nil),            // 10: k3sm.guest.v1.StopRequest
	(*StopResponse)(nil),           // 11: k3sm.guest.v1.StopResponse
	(*GuestSpec)(nil),              // 12: k3sm.guest.v1.GuestSpec
	(*ResolvConf)(nil),             // 13: k3sm.guest.v1.ResolvConf
	(*GuestContainer)(nil),         // 14: k3sm.guest.v1.GuestContainer
	(*GuestMount)(nil),             // 15: k3sm.guest.v1.GuestMount
	(*VMHostSpec)(nil),             // 16: k3sm.guest.v1.VMHostSpec
	(*VMShare)(nil),                // 17: k3sm.guest.v1.VMShare
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
	(*v1.ExecRequest)(nil),         // 19: k3sm.runtime.v1.ExecRequest
	(*v1.GetLogsRequest)(nil),      // 20: k3sm.runtime.v1.GetLogsRequest
	(*v1.AttachRequest)(nil),       // 21: k3sm.runtime.v1.AttachRequest
	(*v1.ExecResponse)(nil),        // 22: k3sm.runtime.v1.ExecResponse
	(*v1.LogEntry)(nil),            // 23: k3sm.runtime.v1.LogEntry
	(*v1.AttachResponse)(nil),      // 24: k3sm.runtime.v1.AttachResponse
}
var file_guest_v1_guest_proto_depIdxs = []int32{
	18, // 0: k3sm.guest.v1.ContainerEvent.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 1: k3sm.guest.v1.ContainerEvent.started:type_name -> k3sm.guest.v1.ContainerStarted
	6,  // 2: k3sm.guest.v1.ContainerEvent.exited:type_name -> k3sm.guest.v1.ContainerExited
	18, // 3: k3sm.guest.v1.StatsResponse.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 4: k3sm.guest.v1.StatsResponse.containers:type_name -> k3sm.guest.v1.GuestContainerStats
	13, // 5: k3sm.guest.v1.GuestSpec.resolv_conf:type_name -> k3sm.guest.v1.ResolvConf
	14, // 6: k3sm.guest.v1.GuestSpec.containers:type_name -> k3sm.guest.v1.GuestContainer
	15, // 7: k3sm.guest.v1.GuestSpec.mounts:type_name -> k3sm.guest.v1.GuestMount
	0,  // 8: k3sm.guest.v1.GuestMount.kind:type_name -> k3sm.guest.v1.GuestMountKind
	17, // 9: k3sm.guest.v1.VMHostSpec.shares:type_name -> k3sm.guest.v1.VMShare
	1,  // 10: k3sm.guest.v1.GuestAgent.Health:input_type -> k3sm.guest.v1.HealthRequest
	3,  // 11: k3sm.guest.v1.GuestAgent.ContainerEvents:input_type -> k3sm.guest.v1.ContainerEventsRequest
	19, // 12: k3sm.guest.v1.GuestAgent.Exec:input_type -> k3sm.runtime.v1.ExecRequest
	20, // 13: k3sm.guest.v1.GuestAgent.Logs:input_type -> k3sm.runtime.v1.GetLogsRequest
	7,  // 14: k3sm.guest.v1.GuestAgent.Stats:input_type -> k3sm.guest.v1.StatsRequest
	10, // 15: k3sm.guest.v1.GuestAgent.Stop:input_type -> k3sm.guest.v1.StopRequest
	21, // 16: k3sm.guest.v1.GuestAgent.Attach:input_type -> k3sm.runtime.v1.AttachRequest
	2,  // 17: k3sm.guest.v1.GuestAgent.Health:output_type -> k3sm.guest.v1.HealthResponse
	4,  // 18: k3sm.guest.v1.GuestAgent.ContainerEvents:output_type -> k3sm.guest.v1.ContainerEvent
	22, // 19: k3sm.guest.v1.GuestAgent.Exec:output_type -> k3sm.runtime.v1.ExecResponse
	23, // 20: k3sm.guest.v1.GuestAgent.Logs:output_type -> k3sm.runtime.v1.LogEntry
	8,  // 21: k3sm.guest.v1.GuestAgent.Stats:output_type -> k3sm.guest.v1.StatsResponse
	11, // 22: k3sm.guest.v1.GuestAgent.Stop:output_type -> k3sm.guest.v1.StopResponse
	24, // 23: k3sm.guest.v1.GuestAgent.Attach:output_type -> k3sm.runtime.v1.AttachResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_guest_v1_guest_proto_init() }
func file_guest_v1_guest_proto_init() {
	if File_guest_v1_guest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guest_v1_guest_proto_rawDesc), len(file_guest_v1_guest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guest_v1_guest_proto_goTypes,
		DependencyIndexes: file_guest_v1_guest_proto_depIdxs,
		EnumInfos:         file_guest_v1_guest_proto_enumTypes,
		MessageInfos:      file_guest_v1_guest_proto_msgTypes,
	}.Build()
	File_guest_v1_guest_proto = out.File
	file_guest_v1_guest_proto_goTypes = nil
	file_guest_v1_guest_proto_depIdxs = nil
}
