// Package shim.v1 is the k3sm per-container shim contract: the gRPC service a
// resident shim process serves for exactly one container, dialed by the node
// runtime daemon over a daemon-private unix socket. The shim owns the
// container's stdio, its log file, and its exit status, so the container's
// output, exit code, and exec surface outlive a restart of the daemon.
//
// WHY THIS IS AN INTERNAL CONTRACT, NOT A PUBLIC ONE: both ends — the runtime
// daemon and the shim — are built from the same runtimed build and versioned by
// that build. A daemon and a shim from different builds are never paired: a
// daemon upgrade recreates every pod, and with it every shim. This file lives in
// k3sm.io/apis only so it shares the module's buf toolchain and codegen.
//
// COMPAT POSTURE: LOCKSTEP. This package is EXPLICITLY NOT covered by
// runtime/v1's "additive-only forever" promise. A change here is a lockstep
// change to both ends in one build. StatusResponse.api_version makes skew
// LEGIBLE: the daemon refuses a shim reporting a different api_version with a
// stated reason. There is no capability negotiation.
//
// SIDE CHANNELS BEYOND THE MESSAGES: the contract relies on three lockstep
// details owned by the runtime build, listed so a reader knows they exist; they
// are not part of the messages. A second unix socket in the same shim directory
// carries file descriptors by SCM_RIGHTS: a tty Exec's pty slave and a rotated
// log file for ReopenLog. Each descriptor is matched to its call by a token in
// gRPC metadata (k3sm-pty-token on Exec, k3sm-log-token on ReopenLog). An Exec
// stream reports its session's pid and start time in response-header metadata
// (k3sm-session-pid, k3sm-session-start), so the caller can end that session
// when the stream ends.
//
// Conventions (kept for consistency with the sibling packages, not as a compat
// promise): field numbers are never renumbered or repurposed within a build
// line, and every message keeps the file convention's `reserved 100 to 149;`
// headroom band.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: shim/v1/shim.proto

package shimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "k3sm.io/apis/runtime/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExitStatus is the child's persisted exit status.
type ExitStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code is the child's exit code when it exited normally (signal == 0).
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// signal is the signal number that terminated the child; 0 means the child
	// exited normally and exit_code is authoritative.
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// finished_at is when the shim observed the child's exit.
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitStatus) Reset() {
	*x = ExitStatus{}
	mi := &file_shim_v1_shim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitStatus) ProtoMessage() {}

func (x *ExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shim_v1_shim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitStatus.ProtoReflect.Descriptor instead.
func (*ExitStatus) Descriptor() ([]byte, []int) {
	return file_shim_v1_shim_proto_rawDescGZIP(), []int{0}
}

func (x *ExitStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExitStatus) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *ExitStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// StatusRequest asks the shim for its status.
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container is an assertion: the shim rejects a name that is not its
	// container.
	Container     string `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_shim_v1_shim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shim_v1_shim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_shim_v1_shim_proto_rawDescGZIP(), []int{1}
}

func (x *StatusRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

// StatusResponse is the shim's identity + child status report.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api_version is the shim/v1 contract version this shim speaks (the Go
	// constant shimv1.APIVersion of its build). Legible, never negotiated: the
	// daemon refuses a shim reporting a different value with a stated reason.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// shim_pid is the shim process's own pid.
	ShimPid int32 `protobuf:"varint,2,opt,name=shim_pid,json=shimPid,proto3" json:"shim_pid,omitempty"`
	// shim_start_unix_nano is the shim process's start time, in Unix
	// nanoseconds; with shim_pid it identifies the shim across pid reuse.
	ShimStartUnixNano int64 `protobuf:"varint,3,opt,name=shim_start_unix_nano,json=shimStartUnixNano,proto3" json:"shim_start_unix_nano,omitempty"`
	// child_pid is the container's child process pid.
	ChildPid int32 `protobuf:"varint,4,opt,name=child_pid,json=childPid,proto3" json:"child_pid,omitempty"`
	// child_start_unix_nano is the child process's start time, in Unix
	// nanoseconds; with child_pid it identifies the child across pid reuse.
	ChildStartUnixNano int64 `protobuf:"varint,5,opt,name=child_start_unix_nano,json=childStartUnixNano,proto3" json:"child_start_unix_nano,omitempty"`
	// running is true while the child has not exited.
	Running bool `protobuf:"varint,6,opt,name=running,proto3" json:"running,omitempty"`
	// exit is set iff the child has exited AND its status has been persisted by
	// the shim. It is the exit authority for the container.
	Exit *ExitStatus `protobuf:"bytes,7,opt,name=exit,proto3" json:"exit,omitempty"`
	// dropped_bytes counts output bytes dropped by the shim's ring buffer since
	// the shim started (a slow log writer or follower never blocks the child).
	DroppedBytes  uint64 `protobuf:"varint,8,opt,name=dropped_bytes,json=droppedBytes,proto3" json:"dropped_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_shim_v1_shim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shim_v1_shim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_shim_v1_shim_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *StatusResponse) GetShimPid() int32 {
	if x != nil {
		return x.ShimPid
	}
	return 0
}

func (x *StatusResponse) GetShimStartUnixNano() int64 {
	if x != nil {
		return x.ShimStartUnixNano
	}
	return 0
}

func (x *StatusResponse) GetChildPid() int32 {
	if x != nil {
		return x.ChildPid
	}
	return 0
}

func (x *StatusResponse) GetChildStartUnixNano() int64 {
	if x != nil {
		return x.ChildStartUnixNano
	}
	return 0
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetExit() *ExitStatus {
	if x != nil {
		return x.Exit
	}
	return nil
}

func (x *StatusResponse) GetDroppedBytes() uint64 {
	if x != nil {
		return x.DroppedBytes
	}
	return 0
}

// FollowRequest subscribes to the container's live output.
type FollowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container is an assertion: the shim rejects a name that is not its
	// container.
	Container     string `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_shim_v1_shim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shim_v1_shim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_shim_v1_shim_proto_rawDescGZIP(), []int{3}
}

func (x *FollowRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

// SignalRequest delivers a signal.
type SignalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container is an assertion: the shim rejects a name that is not its
	// container.
	Container string `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	// signal is the signal number to deliver.
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// group selects the target: true signals the container's process group,
	// false signals only the child.
	Group         bool `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_shim_v1_shim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shim_v1_shim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_shim_v1_shim_proto_rawDescGZIP(), []int{4}
}

func (x *SignalRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *SignalRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *SignalRequest) GetGroup() bool {
	if x != nil {
		return x.Group
	}
	return false
}

// SignalResponse is empty: success is the absence of an error.
type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_shim_v1_shim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shim_v1_shim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_shim_v1_shim_proto_rawDescGZIP(), []int{5}
}

// ReopenLogRequest asks the shim to reopen the container's log file.
type ReopenLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container is an assertion: the shim rejects a name that is not its
	// container.
	Container     string `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReopenLogRequest) Reset() {
	*x = ReopenLogRequest{}
	mi := &file_shim_v1_shim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReopenLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReopenLogRequest) ProtoMessage() {}

func (x *ReopenLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shim_v1_shim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReopenLogRequest.ProtoReflect.Descriptor instead.
func (*ReopenLogRequest) Descriptor() ([]byte, []int) {
	return file_shim_v1_shim_proto_rawDescGZIP(), []int{6}
}

func (x *ReopenLogRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

// ReopenLogResponse is empty: success is the absence of an error.
type ReopenLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReopenLogResponse) Reset() {
	*x = ReopenLogResponse{}
	mi := &file_shim_v1_shim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReopenLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReopenLogResponse) ProtoMessage() {}

func (x *ReopenLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shim_v1_shim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReopenLogResponse.ProtoReflect.Descriptor instead.
func (*ReopenLogResponse) Descriptor() ([]byte, []int) {
	return file_shim_v1_shim_proto_rawDescGZIP(), []int{7}
}

var File_shim_v1_shim_proto protoreflect.FileDescriptor

const file_shim_v1_shim_proto_rawDesc = "" +
	"\n" +
	"\x12shim/v1/shim.proto\x12\fk3sm.shim.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18runtime/v1/runtime.proto\"\x85\x01\n" +
	"\n" +
	"ExitStatus\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\x12;\n" +
	"\vfinished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAtJ\x05\bd\x10\x96\x01\"4\n" +
	"\rStatusRequest\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainerJ\x05\bd\x10\x96\x01\"\xc1\x02\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x19\n" +
	"\bshim_pid\x18\x02 \x01(\x05R\ashimPid\x12/\n" +
	"\x14shim_start_unix_nano\x18\x03 \x01(\x03R\x11shimStartUnixNano\x12\x1b\n" +
	"\tchild_pid\x18\x04 \x01(\x05R\bchildPid\x121\n" +
	"\x15child_start_unix_nano\x18\x05 \x01(\x03R\x12childStartUnixNano\x12\x18\n" +
	"\arunning\x18\x06 \x01(\bR\arunning\x12,\n" +
	"\x04exit\x18\a \x01(\v2\x18.k3sm.shim.v1.ExitStatusR\x04exit\x12#\n" +
	"\rdropped_bytes\x18\b \x01(\x04R\fdroppedBytesJ\x05\bd\x10\x96\x01\"4\n" +
	"\rFollowRequest\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainerJ\x05\bd\x10\x96\x01\"b\n" +
	"\rSignalRequest\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\x12\x14\n" +
	"\x05group\x18\x03 \x01(\bR\x05groupJ\x05\bd\x10\x96\x01\"\x17\n" +
	"\x0eSignalResponseJ\x05\bd\x10\x96\x01\"7\n" +
	"\x10ReopenLogRequest\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainerJ\x05\bd\x10\x96\x01\"\x1a\n" +
	"\x11ReopenLogResponseJ\x05\bd\x10\x96\x012\xfa\x02\n" +
	"\rContainerShim\x12C\n" +
	"\x06Status\x12\x1b.k3sm.shim.v1.StatusRequest\x1a\x1c.k3sm.shim.v1.StatusResponse\x12G\n" +
	"\x04Exec\x12\x1c.k3sm.runtime.v1.ExecRequest\x1a\x1d.k3sm.runtime.v1.ExecResponse(\x010\x01\x12H\n" +
	"\x06Follow\x12\x1b.k3sm.shim.v1.FollowRequest\x1a\x1f.k3sm.runtime.v1.AttachResponse0\x01\x12C\n" +
	"\x06Signal\x12\x1b.k3sm.shim.v1.SignalRequest\x1a\x1c.k3sm.shim.v1.SignalResponse\x12L\n" +
	"\tReopenLog\x12\x1e.k3sm.shim.v1.ReopenLogRequest\x1a\x1f.k3sm.shim.v1.ReopenLogResponseB\x8c\x01\n" +
	"\x10com.k3sm.shim.v1B\tShimProtoP\x01Z\x1bk3sm.io/apis/shim/v1;shimv1\xa2\x02\x03KSX\xaa\x02\fK3sm.Shim.V1\xca\x02\fK3sm\\Shim\\V1\xe2\x02\x18K3sm\\Shim\\V1\\GPBMetadata\xea\x02\x0eK3sm::Shim::V1b\x06proto3"

var (
	file_shim_v1_shim_proto_rawDescOnce sync.Once
	file_shim_v1_shim_proto_rawDescData []byte
)

func file_shim_v1_shim_proto_rawDescGZIP() []byte {
	file_shim_v1_shim_proto_rawDescOnce.Do(func() {
		file_shim_v1_shim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shim_v1_shim_proto_rawDesc), len(file_shim_v1_shim_proto_rawDesc)))
	})
	return file_shim_v1_shim_proto_rawDescData
}

var file_shim_v1_shim_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shim_v1_shim_proto_goTypes = []any{
	(*ExitStatus)(nil),            // 0: k3sm.shim.v1.ExitStatus
	(*StatusRequest)(nil),         // 1: k3sm.shim.v1.StatusRequest
	(*StatusResponse)(nil),        // 2: k3sm.shim.v1.StatusResponse
	(*FollowRequest)(nil),         // 3: k3sm.shim.v1.FollowRequest
	(*SignalRequest)(nil),         // 4: k3sm.shim.v1.SignalRequest
	(*SignalResponse)(nil),        // 5: k3sm.shim.v1.SignalResponse
	(*ReopenLogRequest)(nil),      // 6: k3sm.shim.v1.ReopenLogRequest
	(*ReopenLogResponse)(nil),     // 7: k3sm.shim.v1.ReopenLogResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*v1.ExecRequest)(nil),        // 9: k3sm.runtime.v1.ExecRequest
	(*v1.ExecResponse)(nil),       // 10: k3sm.runtime.v1.ExecResponse
	(*v1.AttachResponse)(nil),     // 11: k3sm.runtime.v1.AttachResponse
}
var file_shim_v1_shim_proto_depIdxs = []int32{
	8,  // 0: k3sm.shim.v1.ExitStatus.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 1: k3sm.shim.v1.StatusResponse.exit:type_name -> k3sm.shim.v1.ExitStatus
	1,  // 2: k3sm.shim.v1.ContainerShim.Status:input_type -> k3sm.shim.v1.StatusRequest
	9,  // 3: k3sm.shim.v1.ContainerShim.Exec:input_type -> k3sm.runtime.v1.ExecRequest
	3,  // 4: k3sm.shim.v1.ContainerShim.Follow:input_type -> k3sm.shim.v1.FollowRequest
	4,  // 5: k3sm.shim.v1.ContainerShim.Signal:input_type -> k3sm.shim.v1.SignalRequest
	6,  // 6: k3sm.shim.v1.ContainerShim.ReopenLog:input_type -> k3sm.shim.v1.ReopenLogRequest
	2,  // 7: k3sm.shim.v1.ContainerShim.Status:output_type -> k3sm.shim.v1.StatusResponse
	10, // 8: k3sm.shim.v1.ContainerShim.Exec:output_type -> k3sm.runtime.v1.ExecResponse
	11, // 9: k3sm.shim.v1.ContainerShim.Follow:output_type -> k3sm.runtime.v1.AttachResponse
	5,  // 10: k3sm.shim.v1.ContainerShim.Signal:output_type -> k3sm.shim.v1.SignalResponse
	7,  // 11: k3sm.shim.v1.ContainerShim.ReopenLog:output_type -> k3sm.shim.v1.ReopenLogResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_shim_v1_shim_proto_init() }
func file_shim_v1_shim_proto_init() {
	if File_shim_v1_shim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shim_v1_shim_proto_rawDesc), len(file_shim_v1_shim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shim_v1_shim_proto_goTypes,
		DependencyIndexes: file_shim_v1_shim_proto_depIdxs,
		MessageInfos:      file_shim_v1_shim_proto_msgTypes,
	}.Build()
	File_shim_v1_shim_proto = out.File
	file_shim_v1_shim_proto_goTypes = nil
	file_shim_v1_shim_proto_depIdxs = nil
}
