// Package shim.v1 is the k3sm per-container shim contract: the gRPC service a
// resident shim process serves for exactly one container, dialed by the node
// runtime daemon over a daemon-private unix socket. The shim owns the
// container's stdio, its log file, and its exit status, so the container's
// output, exit code, and exec surface outlive a restart of the daemon.
//
// WHY THIS IS AN INTERNAL CONTRACT, NOT A PUBLIC ONE: both ends — the runtime
// daemon and the shim — are built from the same runtimed build and versioned by
// that build. A daemon and a shim from different builds are never paired: a
// daemon upgrade recreates every pod, and with it every shim. This file lives in
// k3sm.io/apis only so it shares the module's buf toolchain and codegen.
//
// COMPAT POSTURE: LOCKSTEP. This package is EXPLICITLY NOT covered by
// runtime/v1's "additive-only forever" promise. A change here is a lockstep
// change to both ends in one build. StatusResponse.api_version makes skew
// LEGIBLE: the daemon refuses a shim reporting a different api_version with a
// stated reason. There is no capability negotiation.
//
// SIDE CHANNELS BEYOND THE MESSAGES: the contract relies on three lockstep
// details owned by the runtime build, listed so a reader knows they exist; they
// are not part of the messages. A second unix socket in the same shim directory
// carries file descriptors by SCM_RIGHTS: a tty Exec's pty slave and a rotated
// log file for ReopenLog. Each descriptor is matched to its call by a token in
// gRPC metadata (k3sm-pty-token on Exec, k3sm-log-token on ReopenLog). An Exec
// stream reports its session's pid and start time in response-header metadata
// (k3sm-session-pid, k3sm-session-start), so the caller can end that session
// when the stream ends.
//
// Conventions (kept for consistency with the sibling packages, not as a compat
// promise): field numbers are never renumbered or repurposed within a build
// line, and every message keeps the file convention's `reserved 100 to 149;`
// headroom band.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: shim/v1/shim.proto

package shimv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "k3sm.io/apis/runtime/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerShim_Status_FullMethodName    = "/k3sm.shim.v1.ContainerShim/Status"
	ContainerShim_Exec_FullMethodName      = "/k3sm.shim.v1.ContainerShim/Exec"
	ContainerShim_Follow_FullMethodName    = "/k3sm.shim.v1.ContainerShim/Follow"
	ContainerShim_Signal_FullMethodName    = "/k3sm.shim.v1.ContainerShim/Signal"
	ContainerShim_ReopenLog_FullMethodName = "/k3sm.shim.v1.ContainerShim/ReopenLog"
)

// ContainerShimClient is the client API for ContainerShim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContainerShim is served by the resident per-container shim. One shim hosts
// exactly one container, so every RPC is scoped to that container implicitly.
// Requests still carry `container`, and the shim MUST reject a name that is not
// its container: the name is an assertion that the caller reached the shim it
// meant to reach, not a selector over several.
//
// RPC numbering note: gRPC method names (not numbers) are the wire identity.
type ContainerShimClient interface {
	// Status reports the shim's identity (api_version, its own pid and start
	// time), the child's identity (pid and start time, so a pid reuse is
	// detectable), whether the child is running, its persisted exit status once
	// it has exited, and the ring-buffer drop counter.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Exec runs `kubectl exec` in the container's context, reusing the runtime/v1
	// exec stream messages verbatim. In ExecRequest, container MUST equal the
	// shim's container (the shim rejects any other); the remaining fields keep
	// their runtime/v1 meaning exactly.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.ExecRequest, v1.ExecResponse], error)
	// Follow streams the container's live stdout/stderr from the moment of the
	// call, reusing the runtime/v1 AttachResponse message. There is no replay of
	// earlier output (the log file is the history). The stream ends after the
	// container exits. AttachResponse.exit (ExecResult, a signal death mirrored as
	// 128+signal) is a LIVENESS HINT only — it is never the exit authority;
	// Status.exit is.
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.AttachResponse], error)
	// Signal delivers a signal to the container's process group or to the child
	// alone.
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	// ReopenLog closes and reopens the container's log file at its configured
	// path, so a rotation by the daemon takes effect without losing output.
	ReopenLog(ctx context.Context, in *ReopenLogRequest, opts ...grpc.CallOption) (*ReopenLogResponse, error)
}

type containerShimClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerShimClient(cc grpc.ClientConnInterface) ContainerShimClient {
	return &containerShimClient{cc}
}

func (c *containerShimClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ContainerShim_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerShimClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.ExecRequest, v1.ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContainerShim_ServiceDesc.Streams[0], ContainerShim_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.ExecRequest, v1.ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerShim_ExecClient = grpc.BidiStreamingClient[v1.ExecRequest, v1.ExecResponse]

func (c *containerShimClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.AttachResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContainerShim_ServiceDesc.Streams[1], ContainerShim_Follow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FollowRequest, v1.AttachResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerShim_FollowClient = grpc.ServerStreamingClient[v1.AttachResponse]

func (c *containerShimClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, ContainerShim_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerShimClient) ReopenLog(ctx context.Context, in *ReopenLogRequest, opts ...grpc.CallOption) (*ReopenLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReopenLogResponse)
	err := c.cc.Invoke(ctx, ContainerShim_ReopenLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerShimServer is the server API for ContainerShim service.
// All implementations must embed UnimplementedContainerShimServer
// for forward compatibility.
//
// ContainerShim is served by the resident per-container shim. One shim hosts
// exactly one container, so every RPC is scoped to that container implicitly.
// Requests still carry `container`, and the shim MUST reject a name that is not
// its container: the name is an assertion that the caller reached the shim it
// meant to reach, not a selector over several.
//
// RPC numbering note: gRPC method names (not numbers) are the wire identity.
type ContainerShimServer interface {
	// Status reports the shim's identity (api_version, its own pid and start
	// time), the child's identity (pid and start time, so a pid reuse is
	// detectable), whether the child is running, its persisted exit status once
	// it has exited, and the ring-buffer drop counter.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Exec runs `kubectl exec` in the container's context, reusing the runtime/v1
	// exec stream messages verbatim. In ExecRequest, container MUST equal the
	// shim's container (the shim rejects any other); the remaining fields keep
	// their runtime/v1 meaning exactly.
	Exec(grpc.BidiStreamingServer[v1.ExecRequest, v1.ExecResponse]) error
	// Follow streams the container's live stdout/stderr from the moment of the
	// call, reusing the runtime/v1 AttachResponse message. There is no replay of
	// earlier output (the log file is the history). The stream ends after the
	// container exits. AttachResponse.exit (ExecResult, a signal death mirrored as
	// 128+signal) is a LIVENESS HINT only — it is never the exit authority;
	// Status.exit is.
	Follow(*FollowRequest, grpc.ServerStreamingServer[v1.AttachResponse]) error
	// Signal delivers a signal to the container's process group or to the child
	// alone.
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	// ReopenLog closes and reopens the container's log file at its configured
	// path, so a rotation by the daemon takes effect without losing output.
	ReopenLog(context.Context, *ReopenLogRequest) (*ReopenLogResponse, error)
	mustEmbedUnimplementedContainerShimServer()
}

// UnimplementedContainerShimServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerShimServer struct{}

func (UnimplementedContainerShimServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedContainerShimServer) Exec(grpc.BidiStreamingServer[v1.ExecRequest, v1.ExecResponse]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedContainerShimServer) Follow(*FollowRequest, grpc.ServerStreamingServer[v1.AttachResponse]) error {
	return status.Error(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedContainerShimServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedContainerShimServer) ReopenLog(context.Context, *ReopenLogRequest) (*ReopenLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReopenLog not implemented")
}
func (UnimplementedContainerShimServer) mustEmbedUnimplementedContainerShimServer() {}
func (UnimplementedContainerShimServer) testEmbeddedByValue()                       {}

// UnsafeContainerShimServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerShimServer will
// result in compilation errors.
type UnsafeContainerShimServer interface {
	mustEmbedUnimplementedContainerShimServer()
}

func RegisterContainerShimServer(s grpc.ServiceRegistrar, srv ContainerShimServer) {
	// If the following call panics, it indicates UnimplementedContainerShimServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerShim_ServiceDesc, srv)
}

func _ContainerShim_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerShimServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerShim_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerShimServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerShim_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContainerShimServer).Exec(&grpc.GenericServerStream[v1.ExecRequest, v1.ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerShim_ExecServer = grpc.BidiStreamingServer[v1.ExecRequest, v1.ExecResponse]

func _ContainerShim_Follow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContainerShimServer).Follow(m, &grpc.GenericServerStream[FollowRequest, v1.AttachResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerShim_FollowServer = grpc.ServerStreamingServer[v1.AttachResponse]

func _ContainerShim_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerShimServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerShim_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerShimServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerShim_ReopenLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReopenLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerShimServer).ReopenLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerShim_ReopenLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerShimServer).ReopenLog(ctx, req.(*ReopenLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerShim_ServiceDesc is the grpc.ServiceDesc for ContainerShim service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerShim_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k3sm.shim.v1.ContainerShim",
	HandlerType: (*ContainerShimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ContainerShim_Status_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _ContainerShim_Signal_Handler,
		},
		{
			MethodName: "ReopenLog",
			Handler:    _ContainerShim_ReopenLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _ContainerShim_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Follow",
			Handler:       _ContainerShim_Follow_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "shim/v1/shim.proto",
}
