// images.proto is the k3sm node image contract: the store-facing RPCs the
// `k3sm image` CLI and the node's image-GC caller drive. It is a separate
// service in the same proto package (k3sm.runtime.v1) — the CRI
// RuntimeService/ImageService split. Image verbs and pod verbs are different
// callers' surfaces, so they get different services; they share one package,
// one generated Go package, and one wire namespace, because a second proto
// package or import path would fork the shared-contracts module for no gain.
//
// Stability contract: as in runtime.proto — field numbers are stable and the
// surface is additive-only forever. Never renumber or repurpose a field; never
// reuse a reserved number/name. Every message keeps the file convention's
// `reserved 100 to 149;` headroom band. `buf breaking` (WIRE_JSON) enforces it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: runtime/v1/images.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Images_ListImages_FullMethodName   = "/k3sm.runtime.v1.Images/ListImages"
	Images_ImageFsInfo_FullMethodName  = "/k3sm.runtime.v1.Images/ImageFsInfo"
	Images_RemoveImage_FullMethodName  = "/k3sm.runtime.v1.Images/RemoveImage"
	Images_PruneImages_FullMethodName  = "/k3sm.runtime.v1.Images/PruneImages"
	Images_LoadImage_FullMethodName    = "/k3sm.runtime.v1.Images/LoadImage"
	Images_PullImage_FullMethodName    = "/k3sm.runtime.v1.Images/PullImage"
	Images_TagImage_FullMethodName     = "/k3sm.runtime.v1.Images/TagImage"
	Images_UntagImage_FullMethodName   = "/k3sm.runtime.v1.Images/UntagImage"
	Images_InspectImage_FullMethodName = "/k3sm.runtime.v1.Images/InspectImage"
	Images_SaveImage_FullMethodName    = "/k3sm.runtime.v1.Images/SaveImage"
)

// ImagesClient is the client API for Images service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Images is the node-local image service: pull, list, inspect, measure, tag,
// untag, remove, prune, ingest, and export. It is served by the same native runtime daemon (k3sm.io/runtimed)
// that serves `service Runtime`, on the same listener — the split is about
// which caller a surface belongs to, not about which process serves it.
//
// Trust posture (stated precisely — these RPCs are not "root-only"):
//
//   - In the installed posture the runtime is embedded in-process in the one
//     k3sm binary and serves no socket at all. The only unix-socket listener is
//     created by the standalone k3sm-runtimed daemon binary; an embedded node
//     never constructs one, so it exposes these RPCs to no peer whatsoever.
//
//   - The standalone daemon's socket is guarded by POSIX file mode alone: the
//     socket node is 0600 inside a 0700 parent dir, owned by the daemon's own
//     euid (the unprivileged `_k3sm` user in the shipped posture; root only if
//     an operator chooses to run the daemon as root). There is no LOCAL_PEERCRED
//     differentiation on this socket, and pods commonly share the daemon's uid,
//     because the native hostprocess path has no per-pod uid isolation. Absent
//     an explicit Seatbelt deny of the socket path, a process at that uid is
//     indistinguishable from the CLI. The file mode keeps other uids out; it
//     does not partition the daemon's own uid into callers.
//
//   - Consequence for future work: "narrow these RPCs to a subset of callers",
//     or "let `k3sm image ls` work without sudo", needs a new listener and
//     authorizer design — a second socket with its own ownership, plus an
//     authorizer that can actually tell peers apart — never a permission tweak
//     on this one.
//
//   - The mechanical control lives daemon-side, not here: a proto file cannot
//     assert what listener its service is registered on. The assertion that
//     Images is served by the identical server the Runtime service is
//     registered on — so it inherits exactly this socket and no other — is
//     asserted by a gate in the daemon repo.
//
// Skew: v1 is deliberately reactive. A daemon that predates this service
// returns gRPC UNIMPLEMENTED for every method below, and a client treats that
// status as "this daemon has no image service". Capability-band advertisement
// via GetRuntimeInfoResponse's reserved 100..149 band was considered and
// deferred: it would cost a field plus a producer and a consumer on both sides
// to restate what the status code already carries unambiguously.
type ImagesClient interface {
	// ListImages returns the images recorded in the local store. The entries
	// embed the existing Descriptor / ImageManifest / Platform messages rather
	// than re-spelling digest, size, or media type as parallel scalars.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// ImageFsInfo returns raw statfs-style measurements of the filesystem backing
	// the image store. It is measurement-shaped only — see FilesystemUsage.
	ImageFsInfo(ctx context.Context, in *ImageFsInfoRequest, opts ...grpc.CallOption) (*ImageFsInfoResponse, error)
	// RemoveImage removes an image ROOT from the local index (an untag). Root
	// removal is authorized and local — an explicit operator/lifecycle action,
	// never a side effect of fetched content. It unlinks no blobs: blob deletion
	// happens only in PruneImages, which re-derives reachability first.
	// Idempotent — removing an absent image succeeds.
	RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error)
	// PruneImages deletes unreferenced content. The refusal semantics are
	// daemon-side: deletability is `not reachable(blob, roots)` computed in one
	// transaction over recorded edges, and every unlink re-verifies before it
	// runs (the ratified image-GC provenance model: edges are monotone, roots are
	// digest-pinned, and root removal is authorized and local). This wire carries
	// only the typed outcome: which digests
	// went, and a minimal per-digest reason for each one that was kept, so a
	// dry-run or audit caller can see why a blob survived without the daemon
	// exporting its policy.
	PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error)
	// LoadImage ingests an image archive the client streams — the `k3sm image
	// load` / `import` path.
	//
	// Client-streaming, and the shape is deliberate: the client sends a metadata
	// frame then chunk frames, and the server replies exactly once at the end.
	// Runtime's Exec/Attach/PortForward are bidirectional; this is the file's
	// first client-streaming RPC, because there is nothing for the server to say
	// until the archive is verified and committed.
	//
	// The daemon is the sole store writer on this path: the client opens the
	// operator's archive (the daemon generally cannot read an operator's home)
	// and streams the bytes; it never writes the content store itself.
	//
	// Digest contract: any client-supplied digest or size is advisory. The server
	// must re-hash the received bytes and reject a mismatch before the lease
	// commits — a client-asserted digest is an input to be verified, never a fact
	// to be trusted (every ingest path re-hashes content against its claimed
	// digest before commit).
	//
	// Lease obligation: the server takes its store lease before the first blob
	// commit and records the reference before releasing it. This is stated here
	// only until the store/metastore package can carry it in its own doc.go.
	// TODO: once that package is promoted, re-point this citation there.
	//
	// LoadImage is not a SignaturePolicy checkpoint. Loaded images are
	// provenance-free by design — an operator-CLI-only surface. This RPC neither
	// evaluates nor records a SignaturePolicy; enforcement stays where it already
	// is, at materialize/exec.
	LoadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LoadImageRequest, LoadImageResponse], error)
	// PullImage resolves a reference for a platform and fetches it through the
	// daemon's OWN puller — the same code path a pod-driven pull takes, so it
	// inherits (rather than restates) that path's obligations: every fetched blob
	// is re-hashed against its claimed digest before the lease commits, the
	// disk-pressure gate applies, and the resulting reference is recorded in the
	// local image index. A daemon that served this from a second fetch path would
	// have forked its own verification story.
	//
	// This is explicitly the CLI-pull primitive — `k3sm image pull`. It exists so
	// an operator can WARM and PIN the store ahead of a workload, not so images
	// can arrive by a route pods do not use.
	//
	// Provenance: a successful pull records a reference -> digest index entry — an
	// edge, plus an OPERATOR root over that reference (the ratified image-GC
	// provenance model: edges are monotone, roots are digest-pinned, and root
	// removal is authorized and local). That
	// root is why a pulled-but-unused image survives PruneImages: it stays
	// reachable until the operator removes the name with UntagImage.
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error)
	// TagImage records an ADDITIONAL reference for a manifest digest that is
	// already in the local store: a new (reference x platform) index entry
	// pointing at existing content. It contacts no registry and writes no blob.
	//
	// Additive only, and that is the whole safety argument — a tag can make
	// content reachable, never unreachable. Two consequences are contract, not
	// implementation detail. The target is named by DIGEST and never by another
	// (mutable) tag, because roots are digest-pinned and resolving a name here
	// would let a concurrent re-pull decide what the new tag means. And this RPC
	// never RE-POINTS an existing entry at a different digest: that would drop the
	// old edge, which is a root removal wearing a tag's clothes. Re-pointing is
	// UntagImage then TagImage — two steps the operator explicitly asked for.
	//
	// Status contract: NOT_FOUND when the digest is absent from the store (a tag
	// may not name content the node does not have); FAILED_PRECONDITION when the
	// (reference x platform) key exists and resolves to a different digest;
	// idempotent OK when it already resolves to this digest. platform is part of
	// the key, never a filter.
	TagImage(ctx context.Context, in *TagImageRequest, opts ...grpc.CallOption) (*TagImageResponse, error)
	// UntagImage removes ONE (reference x platform) index entry. It is the
	// provenance model's sanctioned EXPLICIT UNTAG — an authorized, local root
	// removal the operator requested, never a side effect of fetched content.
	//
	// Untag removes a NAME, not bytes. No blob is unlinked here; content is
	// reclaimed only by PruneImages, which re-derives reachability first. So
	// untagging a name that a live pod's root still pins leaves the content
	// reachable and the pod unharmed — that is the point of separating the two
	// verbs, not a limitation of this one.
	//
	// Deliberately distinct from RemoveImage, whose refusal stands: the shipped
	// daemon answers RemoveImage with UNIMPLEMENTED as a design statement, because
	// image roots are per-pod records and a request shaped as "remove this image"
	// does not say which root the caller owns. UntagImage names exactly one
	// operator-owned entry, which is why it is the removal that can be granted.
	//
	// Status contract: NOT_FOUND when the entry does not exist — untag is
	// deliberately NOT idempotent-by-silence, since the caller asked to remove a
	// specific name; FAILED_PRECONDITION, removing nothing, when platform is unset
	// and the reference has more than one platform entry (an ambiguous untag is
	// never a guess) or when digest is set and the entry resolves elsewhere.
	UntagImage(ctx context.Context, in *UntagImageRequest, opts ...grpc.CallOption) (*UntagImageResponse, error)
	// InspectImage reports what the store knows about one image — the `docker
	// inspect` analog, and the read side of the tag verbs above.
	//
	// The target is a (reference x platform) key or a manifest digest; a digest
	// names content directly and needs no platform. Strictly read-only: it
	// resolves nothing against a registry, takes no lease and records no root, so
	// it can never make content reachable.
	//
	// The entry itself is the EXISTING Image wrapper, so digest, manifest media
	// type and size, resolved platform, and the config and layer descriptors with
	// their own digests and sizes are read out of the same Descriptor /
	// ImageManifest messages ListImages returns; an inspect that re-spelled them
	// would drift from the list on the first divergent edit. What Image cannot
	// carry is the decoded image config, which is ImageConfig below.
	//
	// Every response field is independently optional: an absent field means the
	// daemon reported no value for that fact, never that the image asserts an
	// empty one. That is what lets a later daemon report more without a wire
	// change.
	InspectImage(ctx context.Context, in *InspectImageRequest, opts ...grpc.CallOption) (*InspectImageResponse, error)
	// SaveImage streams one image OUT of the store as a tarred OCI image layout —
	// the `docker save` analog, and the exact inverse of LoadImage's direction.
	//
	// Server-streaming, mirroring LoadImage's framing in reverse: the server sends
	// chunk frames carrying bytes and nothing else, then exactly ONE terminal
	// frame that carries no chunk and instead reports the exported manifest digest
	// and the byte count the server sent. A client that reaches the end of the
	// stream without a terminal frame has a truncated archive and must discard it.
	//
	// One (reference x platform) per call, like every other verb here: exporting a
	// whole multi-platform index is a different archive shape and is not v1.
	//
	// Export takes no lease, records no root and unlinks nothing. The client is
	// the sole writer of the operator's file, the mirror of LoadImage's rule that
	// the daemon is the sole writer of the store: the daemon generally cannot
	// write into an operator's home and must not try.
	SaveImage(ctx context.Context, in *SaveImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SaveImageResponse], error)
}

type imagesClient struct {
	cc grpc.ClientConnInterface
}

func NewImagesClient(cc grpc.ClientConnInterface) ImagesClient {
	return &imagesClient{cc}
}

func (c *imagesClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, Images_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) ImageFsInfo(ctx context.Context, in *ImageFsInfoRequest, opts ...grpc.CallOption) (*ImageFsInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageFsInfoResponse)
	err := c.cc.Invoke(ctx, Images_ImageFsInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveImageResponse)
	err := c.cc.Invoke(ctx, Images_RemoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneImagesResponse)
	err := c.cc.Invoke(ctx, Images_PruneImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) LoadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LoadImageRequest, LoadImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Images_ServiceDesc.Streams[0], Images_LoadImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoadImageRequest, LoadImageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Images_LoadImageClient = grpc.ClientStreamingClient[LoadImageRequest, LoadImageResponse]

func (c *imagesClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullImageResponse)
	err := c.cc.Invoke(ctx, Images_PullImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) TagImage(ctx context.Context, in *TagImageRequest, opts ...grpc.CallOption) (*TagImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagImageResponse)
	err := c.cc.Invoke(ctx, Images_TagImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) UntagImage(ctx context.Context, in *UntagImageRequest, opts ...grpc.CallOption) (*UntagImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UntagImageResponse)
	err := c.cc.Invoke(ctx, Images_UntagImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) InspectImage(ctx context.Context, in *InspectImageRequest, opts ...grpc.CallOption) (*InspectImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectImageResponse)
	err := c.cc.Invoke(ctx, Images_InspectImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) SaveImage(ctx context.Context, in *SaveImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SaveImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Images_ServiceDesc.Streams[1], Images_SaveImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SaveImageRequest, SaveImageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Images_SaveImageClient = grpc.ServerStreamingClient[SaveImageResponse]

// ImagesServer is the server API for Images service.
// All implementations must embed UnimplementedImagesServer
// for forward compatibility.
//
// Images is the node-local image service: pull, list, inspect, measure, tag,
// untag, remove, prune, ingest, and export. It is served by the same native runtime daemon (k3sm.io/runtimed)
// that serves `service Runtime`, on the same listener — the split is about
// which caller a surface belongs to, not about which process serves it.
//
// Trust posture (stated precisely — these RPCs are not "root-only"):
//
//   - In the installed posture the runtime is embedded in-process in the one
//     k3sm binary and serves no socket at all. The only unix-socket listener is
//     created by the standalone k3sm-runtimed daemon binary; an embedded node
//     never constructs one, so it exposes these RPCs to no peer whatsoever.
//
//   - The standalone daemon's socket is guarded by POSIX file mode alone: the
//     socket node is 0600 inside a 0700 parent dir, owned by the daemon's own
//     euid (the unprivileged `_k3sm` user in the shipped posture; root only if
//     an operator chooses to run the daemon as root). There is no LOCAL_PEERCRED
//     differentiation on this socket, and pods commonly share the daemon's uid,
//     because the native hostprocess path has no per-pod uid isolation. Absent
//     an explicit Seatbelt deny of the socket path, a process at that uid is
//     indistinguishable from the CLI. The file mode keeps other uids out; it
//     does not partition the daemon's own uid into callers.
//
//   - Consequence for future work: "narrow these RPCs to a subset of callers",
//     or "let `k3sm image ls` work without sudo", needs a new listener and
//     authorizer design — a second socket with its own ownership, plus an
//     authorizer that can actually tell peers apart — never a permission tweak
//     on this one.
//
//   - The mechanical control lives daemon-side, not here: a proto file cannot
//     assert what listener its service is registered on. The assertion that
//     Images is served by the identical server the Runtime service is
//     registered on — so it inherits exactly this socket and no other — is
//     asserted by a gate in the daemon repo.
//
// Skew: v1 is deliberately reactive. A daemon that predates this service
// returns gRPC UNIMPLEMENTED for every method below, and a client treats that
// status as "this daemon has no image service". Capability-band advertisement
// via GetRuntimeInfoResponse's reserved 100..149 band was considered and
// deferred: it would cost a field plus a producer and a consumer on both sides
// to restate what the status code already carries unambiguously.
type ImagesServer interface {
	// ListImages returns the images recorded in the local store. The entries
	// embed the existing Descriptor / ImageManifest / Platform messages rather
	// than re-spelling digest, size, or media type as parallel scalars.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// ImageFsInfo returns raw statfs-style measurements of the filesystem backing
	// the image store. It is measurement-shaped only — see FilesystemUsage.
	ImageFsInfo(context.Context, *ImageFsInfoRequest) (*ImageFsInfoResponse, error)
	// RemoveImage removes an image ROOT from the local index (an untag). Root
	// removal is authorized and local — an explicit operator/lifecycle action,
	// never a side effect of fetched content. It unlinks no blobs: blob deletion
	// happens only in PruneImages, which re-derives reachability first.
	// Idempotent — removing an absent image succeeds.
	RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error)
	// PruneImages deletes unreferenced content. The refusal semantics are
	// daemon-side: deletability is `not reachable(blob, roots)` computed in one
	// transaction over recorded edges, and every unlink re-verifies before it
	// runs (the ratified image-GC provenance model: edges are monotone, roots are
	// digest-pinned, and root removal is authorized and local). This wire carries
	// only the typed outcome: which digests
	// went, and a minimal per-digest reason for each one that was kept, so a
	// dry-run or audit caller can see why a blob survived without the daemon
	// exporting its policy.
	PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error)
	// LoadImage ingests an image archive the client streams — the `k3sm image
	// load` / `import` path.
	//
	// Client-streaming, and the shape is deliberate: the client sends a metadata
	// frame then chunk frames, and the server replies exactly once at the end.
	// Runtime's Exec/Attach/PortForward are bidirectional; this is the file's
	// first client-streaming RPC, because there is nothing for the server to say
	// until the archive is verified and committed.
	//
	// The daemon is the sole store writer on this path: the client opens the
	// operator's archive (the daemon generally cannot read an operator's home)
	// and streams the bytes; it never writes the content store itself.
	//
	// Digest contract: any client-supplied digest or size is advisory. The server
	// must re-hash the received bytes and reject a mismatch before the lease
	// commits — a client-asserted digest is an input to be verified, never a fact
	// to be trusted (every ingest path re-hashes content against its claimed
	// digest before commit).
	//
	// Lease obligation: the server takes its store lease before the first blob
	// commit and records the reference before releasing it. This is stated here
	// only until the store/metastore package can carry it in its own doc.go.
	// TODO: once that package is promoted, re-point this citation there.
	//
	// LoadImage is not a SignaturePolicy checkpoint. Loaded images are
	// provenance-free by design — an operator-CLI-only surface. This RPC neither
	// evaluates nor records a SignaturePolicy; enforcement stays where it already
	// is, at materialize/exec.
	LoadImage(grpc.ClientStreamingServer[LoadImageRequest, LoadImageResponse]) error
	// PullImage resolves a reference for a platform and fetches it through the
	// daemon's OWN puller — the same code path a pod-driven pull takes, so it
	// inherits (rather than restates) that path's obligations: every fetched blob
	// is re-hashed against its claimed digest before the lease commits, the
	// disk-pressure gate applies, and the resulting reference is recorded in the
	// local image index. A daemon that served this from a second fetch path would
	// have forked its own verification story.
	//
	// This is explicitly the CLI-pull primitive — `k3sm image pull`. It exists so
	// an operator can WARM and PIN the store ahead of a workload, not so images
	// can arrive by a route pods do not use.
	//
	// Provenance: a successful pull records a reference -> digest index entry — an
	// edge, plus an OPERATOR root over that reference (the ratified image-GC
	// provenance model: edges are monotone, roots are digest-pinned, and root
	// removal is authorized and local). That
	// root is why a pulled-but-unused image survives PruneImages: it stays
	// reachable until the operator removes the name with UntagImage.
	PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error)
	// TagImage records an ADDITIONAL reference for a manifest digest that is
	// already in the local store: a new (reference x platform) index entry
	// pointing at existing content. It contacts no registry and writes no blob.
	//
	// Additive only, and that is the whole safety argument — a tag can make
	// content reachable, never unreachable. Two consequences are contract, not
	// implementation detail. The target is named by DIGEST and never by another
	// (mutable) tag, because roots are digest-pinned and resolving a name here
	// would let a concurrent re-pull decide what the new tag means. And this RPC
	// never RE-POINTS an existing entry at a different digest: that would drop the
	// old edge, which is a root removal wearing a tag's clothes. Re-pointing is
	// UntagImage then TagImage — two steps the operator explicitly asked for.
	//
	// Status contract: NOT_FOUND when the digest is absent from the store (a tag
	// may not name content the node does not have); FAILED_PRECONDITION when the
	// (reference x platform) key exists and resolves to a different digest;
	// idempotent OK when it already resolves to this digest. platform is part of
	// the key, never a filter.
	TagImage(context.Context, *TagImageRequest) (*TagImageResponse, error)
	// UntagImage removes ONE (reference x platform) index entry. It is the
	// provenance model's sanctioned EXPLICIT UNTAG — an authorized, local root
	// removal the operator requested, never a side effect of fetched content.
	//
	// Untag removes a NAME, not bytes. No blob is unlinked here; content is
	// reclaimed only by PruneImages, which re-derives reachability first. So
	// untagging a name that a live pod's root still pins leaves the content
	// reachable and the pod unharmed — that is the point of separating the two
	// verbs, not a limitation of this one.
	//
	// Deliberately distinct from RemoveImage, whose refusal stands: the shipped
	// daemon answers RemoveImage with UNIMPLEMENTED as a design statement, because
	// image roots are per-pod records and a request shaped as "remove this image"
	// does not say which root the caller owns. UntagImage names exactly one
	// operator-owned entry, which is why it is the removal that can be granted.
	//
	// Status contract: NOT_FOUND when the entry does not exist — untag is
	// deliberately NOT idempotent-by-silence, since the caller asked to remove a
	// specific name; FAILED_PRECONDITION, removing nothing, when platform is unset
	// and the reference has more than one platform entry (an ambiguous untag is
	// never a guess) or when digest is set and the entry resolves elsewhere.
	UntagImage(context.Context, *UntagImageRequest) (*UntagImageResponse, error)
	// InspectImage reports what the store knows about one image — the `docker
	// inspect` analog, and the read side of the tag verbs above.
	//
	// The target is a (reference x platform) key or a manifest digest; a digest
	// names content directly and needs no platform. Strictly read-only: it
	// resolves nothing against a registry, takes no lease and records no root, so
	// it can never make content reachable.
	//
	// The entry itself is the EXISTING Image wrapper, so digest, manifest media
	// type and size, resolved platform, and the config and layer descriptors with
	// their own digests and sizes are read out of the same Descriptor /
	// ImageManifest messages ListImages returns; an inspect that re-spelled them
	// would drift from the list on the first divergent edit. What Image cannot
	// carry is the decoded image config, which is ImageConfig below.
	//
	// Every response field is independently optional: an absent field means the
	// daemon reported no value for that fact, never that the image asserts an
	// empty one. That is what lets a later daemon report more without a wire
	// change.
	InspectImage(context.Context, *InspectImageRequest) (*InspectImageResponse, error)
	// SaveImage streams one image OUT of the store as a tarred OCI image layout —
	// the `docker save` analog, and the exact inverse of LoadImage's direction.
	//
	// Server-streaming, mirroring LoadImage's framing in reverse: the server sends
	// chunk frames carrying bytes and nothing else, then exactly ONE terminal
	// frame that carries no chunk and instead reports the exported manifest digest
	// and the byte count the server sent. A client that reaches the end of the
	// stream without a terminal frame has a truncated archive and must discard it.
	//
	// One (reference x platform) per call, like every other verb here: exporting a
	// whole multi-platform index is a different archive shape and is not v1.
	//
	// Export takes no lease, records no root and unlinks nothing. The client is
	// the sole writer of the operator's file, the mirror of LoadImage's rule that
	// the daemon is the sole writer of the store: the daemon generally cannot
	// write into an operator's home and must not try.
	SaveImage(*SaveImageRequest, grpc.ServerStreamingServer[SaveImageResponse]) error
	mustEmbedUnimplementedImagesServer()
}

// UnimplementedImagesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImagesServer struct{}

func (UnimplementedImagesServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedImagesServer) ImageFsInfo(context.Context, *ImageFsInfoRequest) (*ImageFsInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageFsInfo not implemented")
}
func (UnimplementedImagesServer) RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveImage not implemented")
}
func (UnimplementedImagesServer) PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneImages not implemented")
}
func (UnimplementedImagesServer) LoadImage(grpc.ClientStreamingServer[LoadImageRequest, LoadImageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method LoadImage not implemented")
}
func (UnimplementedImagesServer) PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedImagesServer) TagImage(context.Context, *TagImageRequest) (*TagImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagImage not implemented")
}
func (UnimplementedImagesServer) UntagImage(context.Context, *UntagImageRequest) (*UntagImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UntagImage not implemented")
}
func (UnimplementedImagesServer) InspectImage(context.Context, *InspectImageRequest) (*InspectImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectImage not implemented")
}
func (UnimplementedImagesServer) SaveImage(*SaveImageRequest, grpc.ServerStreamingServer[SaveImageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SaveImage not implemented")
}
func (UnimplementedImagesServer) mustEmbedUnimplementedImagesServer() {}
func (UnimplementedImagesServer) testEmbeddedByValue()                {}

// UnsafeImagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagesServer will
// result in compilation errors.
type UnsafeImagesServer interface {
	mustEmbedUnimplementedImagesServer()
}

func RegisterImagesServer(s grpc.ServiceRegistrar, srv ImagesServer) {
	// If the following call pancis, it indicates UnimplementedImagesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Images_ServiceDesc, srv)
}

func _Images_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_ImageFsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageFsInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ImageFsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_ImageFsInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ImageFsInfo(ctx, req.(*ImageFsInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_RemoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).RemoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_RemoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).RemoveImage(ctx, req.(*RemoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_PruneImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).PruneImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_PruneImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).PruneImages(ctx, req.(*PruneImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_LoadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImagesServer).LoadImage(&grpc.GenericServerStream[LoadImageRequest, LoadImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Images_LoadImageServer = grpc.ClientStreamingServer[LoadImageRequest, LoadImageResponse]

func _Images_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).PullImage(ctx, req.(*PullImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_TagImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).TagImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_TagImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).TagImage(ctx, req.(*TagImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_UntagImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntagImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).UntagImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_UntagImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).UntagImage(ctx, req.(*UntagImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_InspectImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).InspectImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_InspectImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).InspectImage(ctx, req.(*InspectImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_SaveImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SaveImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImagesServer).SaveImage(m, &grpc.GenericServerStream[SaveImageRequest, SaveImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Images_SaveImageServer = grpc.ServerStreamingServer[SaveImageResponse]

// Images_ServiceDesc is the grpc.ServiceDesc for Images service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Images_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k3sm.runtime.v1.Images",
	HandlerType: (*ImagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _Images_ListImages_Handler,
		},
		{
			MethodName: "ImageFsInfo",
			Handler:    _Images_ImageFsInfo_Handler,
		},
		{
			MethodName: "RemoveImage",
			Handler:    _Images_RemoveImage_Handler,
		},
		{
			MethodName: "PruneImages",
			Handler:    _Images_PruneImages_Handler,
		},
		{
			MethodName: "PullImage",
			Handler:    _Images_PullImage_Handler,
		},
		{
			MethodName: "TagImage",
			Handler:    _Images_TagImage_Handler,
		},
		{
			MethodName: "UntagImage",
			Handler:    _Images_UntagImage_Handler,
		},
		{
			MethodName: "InspectImage",
			Handler:    _Images_InspectImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoadImage",
			Handler:       _Images_LoadImage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SaveImage",
			Handler:       _Images_SaveImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runtime/v1/images.proto",
}
