// images.proto is the k3sm node IMAGE contract: the store-facing RPCs the
// `k3sm image` CLI and the node's image-GC caller drive. It is a SEPARATE
// SERVICE IN THE SAME PROTO PACKAGE (k3sm.runtime.v1) — the CRI
// RuntimeService/ImageService split. Image verbs and pod verbs are different
// callers' surfaces, so they get different services; they share one package,
// one generated Go package, and one wire namespace, because a second proto
// package or import path would fork the shared-contracts module for no gain.
//
// Stability contract: as in runtime.proto — field numbers are STABLE and the
// surface is ADDITIVE-ONLY forever. Never renumber or repurpose a field; never
// reuse a reserved number/name. Every message keeps the file convention's
// `reserved 100 to 149;` headroom band. `buf breaking` (WIRE_JSON) enforces it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: runtime/v1/images.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Images_ListImages_FullMethodName  = "/k3sm.runtime.v1.Images/ListImages"
	Images_ImageFsInfo_FullMethodName = "/k3sm.runtime.v1.Images/ImageFsInfo"
	Images_RemoveImage_FullMethodName = "/k3sm.runtime.v1.Images/RemoveImage"
	Images_PruneImages_FullMethodName = "/k3sm.runtime.v1.Images/PruneImages"
	Images_LoadImage_FullMethodName   = "/k3sm.runtime.v1.Images/LoadImage"
)

// ImagesClient is the client API for Images service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Images is the node-local image service: list, measure, remove, prune, and
// ingest. It is served by the same native runtime daemon (k3sm.io/runtimed)
// that serves `service Runtime`, on the same listener — the split is about
// which CALLER a surface belongs to, not about which process serves it.
//
// TRUST POSTURE (stated precisely — these RPCs are NOT "root-only"):
//
//   - In the INSTALLED posture the runtime is EMBEDDED IN-PROCESS in the one
//     k3sm binary and serves NO SOCKET AT ALL. The only unix-socket listener is
//     created by the standalone k3sm-runtimed daemon binary; an embedded node
//     never constructs one, so it exposes these RPCs to no peer whatsoever.
//
//   - The standalone daemon's socket is guarded by POSIX FILE MODE ALONE: the
//     socket node is 0600 inside a 0700 parent dir, owned by the daemon's own
//     euid (the unprivileged `_k3sm` user in the shipped posture; root only if
//     an operator chooses to run the daemon as root). There is NO LOCAL_PEERCRED
//     differentiation on this socket — the server installs no peer-credential
//     check — and pods commonly share the daemon's uid, because the native
//     hostprocess path has no per-pod uid isolation. Absent an explicit Seatbelt
//     deny of the socket path, a process at that uid is indistinguishable from
//     the CLI. The file mode keeps OTHER uids out; it does not partition the
//     daemon's own uid into callers.
//
//   - Consequence for future work: "narrow these RPCs to a subset of callers",
//     or "let `k3sm image ls` work without sudo", is a NEW LISTENER / AUTHZ
//     DESIGN — a second socket with its own ownership, plus an authorizer that
//     can actually tell peers apart — never a permission tweak on this one.
//
//   - The MECHANICAL control lives daemon-side, not here: a proto file cannot
//     assert what listener its service is registered on. The assertion that
//     Images is served by the IDENTICAL server the Runtime service is
//     registered on — so it inherits exactly this socket and no other — is
//     B130b's gate, in the daemon repo.
//
// SKEW (v1 is DELIBERATELY REACTIVE): a daemon that predates this service
// returns gRPC UNIMPLEMENTED for every method below, and a client treats that
// status as "this daemon has no image service". Capability-band advertisement
// via GetRuntimeInfoResponse's reserved 100..149 band was considered and is
// DEFERRED: it would cost a field plus a producer and a consumer on both sides
// to restate what the status code already carries unambiguously. Recorded here
// so a later reader does not re-derive the question and file it as an omission.
type ImagesClient interface {
	// ListImages returns the images recorded in the local store. The entries
	// embed the existing Descriptor / ImageManifest / Platform messages rather
	// than re-spelling digest, size, or media type as parallel scalars.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// ImageFsInfo returns raw statfs-style measurements of the filesystem backing
	// the image store. It is MEASUREMENT-SHAPED ONLY — see FilesystemUsage.
	ImageFsInfo(ctx context.Context, in *ImageFsInfoRequest, opts ...grpc.CallOption) (*ImageFsInfoResponse, error)
	// RemoveImage removes an image ROOT from the local index (an untag). Root
	// removal is authorized and local — an explicit operator/lifecycle action,
	// never a side effect of fetched content. It unlinks no blobs: blob deletion
	// happens only in PruneImages, which re-derives reachability first.
	// Idempotent — removing an absent image succeeds.
	RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error)
	// PruneImages deletes unreferenced content. The REFUSAL SEMANTICS are
	// daemon-side: deletability is `not reachable(blob, roots)` computed in one
	// transaction over recorded edges, and every unlink re-verifies before it
	// runs (the ratified image-GC provenance model — the M12 images plan,
	// Resolution 13). This wire carries only the TYPED OUTCOME: which digests
	// went, and a minimal per-digest reason for each one that was kept, so a
	// dry-run or audit caller can see WHY a blob survived without the daemon
	// exporting its policy.
	PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error)
	// LoadImage ingests an image archive the client streams — the `k3sm image
	// load` / `import` path.
	//
	// CLIENT-STREAMING, and the shape is deliberate: the client sends a metadata
	// frame then chunk frames, and the server replies exactly once at the end.
	// Runtime's Exec/Attach/PortForward are BIDIRECTIONAL; this is the file's
	// first client-streaming RPC, because there is nothing for the server to say
	// until the archive is verified and committed.
	//
	// THE DAEMON IS THE SOLE STORE WRITER on this path: the client opens the
	// operator's archive (the daemon generally cannot read an operator's home)
	// and streams the bytes; it never writes the content store itself. See the
	// M12 images plan, Resolution 8 (as AMENDED 2026-08-09).
	//
	// DIGEST CONTRACT: any client-supplied digest or size is ADVISORY. The server
	// MUST re-hash the received bytes and reject a mismatch BEFORE the lease
	// commits — a client-asserted digest is an input to be verified, never a fact
	// to be trusted (the M12 images plan, Resolution 8: every ingest path
	// re-hashes content against its claimed digest before commit).
	//
	// LEASE OBLIGATION: the server takes its store lease before the first blob
	// commit and records the reference before releasing it. Citation is
	// TRANSITIONAL — the M12 images plan, Resolution 13(c). TODO(B128): once the
	// store/metastore package is promoted and states this obligation in its own
	// doc.go, re-point this citation at that package and drop the plan reference.
	//
	// LoadImage is NOT a SignaturePolicy CHECKPOINT. Loaded images are
	// PROVENANCE-FREE BY DESIGN — an operator-CLI-only surface (the M12 images
	// plan, section M12.2). This RPC neither evaluates nor records a
	// SignaturePolicy; enforcement stays where it already is, at materialize/exec.
	LoadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LoadImageRequest, LoadImageResponse], error)
}

type imagesClient struct {
	cc grpc.ClientConnInterface
}

func NewImagesClient(cc grpc.ClientConnInterface) ImagesClient {
	return &imagesClient{cc}
}

func (c *imagesClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, Images_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) ImageFsInfo(ctx context.Context, in *ImageFsInfoRequest, opts ...grpc.CallOption) (*ImageFsInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageFsInfoResponse)
	err := c.cc.Invoke(ctx, Images_ImageFsInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveImageResponse)
	err := c.cc.Invoke(ctx, Images_RemoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneImagesResponse)
	err := c.cc.Invoke(ctx, Images_PruneImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) LoadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LoadImageRequest, LoadImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Images_ServiceDesc.Streams[0], Images_LoadImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoadImageRequest, LoadImageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Images_LoadImageClient = grpc.ClientStreamingClient[LoadImageRequest, LoadImageResponse]

// ImagesServer is the server API for Images service.
// All implementations must embed UnimplementedImagesServer
// for forward compatibility.
//
// Images is the node-local image service: list, measure, remove, prune, and
// ingest. It is served by the same native runtime daemon (k3sm.io/runtimed)
// that serves `service Runtime`, on the same listener — the split is about
// which CALLER a surface belongs to, not about which process serves it.
//
// TRUST POSTURE (stated precisely — these RPCs are NOT "root-only"):
//
//   - In the INSTALLED posture the runtime is EMBEDDED IN-PROCESS in the one
//     k3sm binary and serves NO SOCKET AT ALL. The only unix-socket listener is
//     created by the standalone k3sm-runtimed daemon binary; an embedded node
//     never constructs one, so it exposes these RPCs to no peer whatsoever.
//
//   - The standalone daemon's socket is guarded by POSIX FILE MODE ALONE: the
//     socket node is 0600 inside a 0700 parent dir, owned by the daemon's own
//     euid (the unprivileged `_k3sm` user in the shipped posture; root only if
//     an operator chooses to run the daemon as root). There is NO LOCAL_PEERCRED
//     differentiation on this socket — the server installs no peer-credential
//     check — and pods commonly share the daemon's uid, because the native
//     hostprocess path has no per-pod uid isolation. Absent an explicit Seatbelt
//     deny of the socket path, a process at that uid is indistinguishable from
//     the CLI. The file mode keeps OTHER uids out; it does not partition the
//     daemon's own uid into callers.
//
//   - Consequence for future work: "narrow these RPCs to a subset of callers",
//     or "let `k3sm image ls` work without sudo", is a NEW LISTENER / AUTHZ
//     DESIGN — a second socket with its own ownership, plus an authorizer that
//     can actually tell peers apart — never a permission tweak on this one.
//
//   - The MECHANICAL control lives daemon-side, not here: a proto file cannot
//     assert what listener its service is registered on. The assertion that
//     Images is served by the IDENTICAL server the Runtime service is
//     registered on — so it inherits exactly this socket and no other — is
//     B130b's gate, in the daemon repo.
//
// SKEW (v1 is DELIBERATELY REACTIVE): a daemon that predates this service
// returns gRPC UNIMPLEMENTED for every method below, and a client treats that
// status as "this daemon has no image service". Capability-band advertisement
// via GetRuntimeInfoResponse's reserved 100..149 band was considered and is
// DEFERRED: it would cost a field plus a producer and a consumer on both sides
// to restate what the status code already carries unambiguously. Recorded here
// so a later reader does not re-derive the question and file it as an omission.
type ImagesServer interface {
	// ListImages returns the images recorded in the local store. The entries
	// embed the existing Descriptor / ImageManifest / Platform messages rather
	// than re-spelling digest, size, or media type as parallel scalars.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// ImageFsInfo returns raw statfs-style measurements of the filesystem backing
	// the image store. It is MEASUREMENT-SHAPED ONLY — see FilesystemUsage.
	ImageFsInfo(context.Context, *ImageFsInfoRequest) (*ImageFsInfoResponse, error)
	// RemoveImage removes an image ROOT from the local index (an untag). Root
	// removal is authorized and local — an explicit operator/lifecycle action,
	// never a side effect of fetched content. It unlinks no blobs: blob deletion
	// happens only in PruneImages, which re-derives reachability first.
	// Idempotent — removing an absent image succeeds.
	RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error)
	// PruneImages deletes unreferenced content. The REFUSAL SEMANTICS are
	// daemon-side: deletability is `not reachable(blob, roots)` computed in one
	// transaction over recorded edges, and every unlink re-verifies before it
	// runs (the ratified image-GC provenance model — the M12 images plan,
	// Resolution 13). This wire carries only the TYPED OUTCOME: which digests
	// went, and a minimal per-digest reason for each one that was kept, so a
	// dry-run or audit caller can see WHY a blob survived without the daemon
	// exporting its policy.
	PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error)
	// LoadImage ingests an image archive the client streams — the `k3sm image
	// load` / `import` path.
	//
	// CLIENT-STREAMING, and the shape is deliberate: the client sends a metadata
	// frame then chunk frames, and the server replies exactly once at the end.
	// Runtime's Exec/Attach/PortForward are BIDIRECTIONAL; this is the file's
	// first client-streaming RPC, because there is nothing for the server to say
	// until the archive is verified and committed.
	//
	// THE DAEMON IS THE SOLE STORE WRITER on this path: the client opens the
	// operator's archive (the daemon generally cannot read an operator's home)
	// and streams the bytes; it never writes the content store itself. See the
	// M12 images plan, Resolution 8 (as AMENDED 2026-08-09).
	//
	// DIGEST CONTRACT: any client-supplied digest or size is ADVISORY. The server
	// MUST re-hash the received bytes and reject a mismatch BEFORE the lease
	// commits — a client-asserted digest is an input to be verified, never a fact
	// to be trusted (the M12 images plan, Resolution 8: every ingest path
	// re-hashes content against its claimed digest before commit).
	//
	// LEASE OBLIGATION: the server takes its store lease before the first blob
	// commit and records the reference before releasing it. Citation is
	// TRANSITIONAL — the M12 images plan, Resolution 13(c). TODO(B128): once the
	// store/metastore package is promoted and states this obligation in its own
	// doc.go, re-point this citation at that package and drop the plan reference.
	//
	// LoadImage is NOT a SignaturePolicy CHECKPOINT. Loaded images are
	// PROVENANCE-FREE BY DESIGN — an operator-CLI-only surface (the M12 images
	// plan, section M12.2). This RPC neither evaluates nor records a
	// SignaturePolicy; enforcement stays where it already is, at materialize/exec.
	LoadImage(grpc.ClientStreamingServer[LoadImageRequest, LoadImageResponse]) error
	mustEmbedUnimplementedImagesServer()
}

// UnimplementedImagesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImagesServer struct{}

func (UnimplementedImagesServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedImagesServer) ImageFsInfo(context.Context, *ImageFsInfoRequest) (*ImageFsInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageFsInfo not implemented")
}
func (UnimplementedImagesServer) RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveImage not implemented")
}
func (UnimplementedImagesServer) PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneImages not implemented")
}
func (UnimplementedImagesServer) LoadImage(grpc.ClientStreamingServer[LoadImageRequest, LoadImageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method LoadImage not implemented")
}
func (UnimplementedImagesServer) mustEmbedUnimplementedImagesServer() {}
func (UnimplementedImagesServer) testEmbeddedByValue()                {}

// UnsafeImagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagesServer will
// result in compilation errors.
type UnsafeImagesServer interface {
	mustEmbedUnimplementedImagesServer()
}

func RegisterImagesServer(s grpc.ServiceRegistrar, srv ImagesServer) {
	// If the following call pancis, it indicates UnimplementedImagesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Images_ServiceDesc, srv)
}

func _Images_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_ImageFsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageFsInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ImageFsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_ImageFsInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ImageFsInfo(ctx, req.(*ImageFsInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_RemoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).RemoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_RemoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).RemoveImage(ctx, req.(*RemoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_PruneImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).PruneImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_PruneImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).PruneImages(ctx, req.(*PruneImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_LoadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImagesServer).LoadImage(&grpc.GenericServerStream[LoadImageRequest, LoadImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Images_LoadImageServer = grpc.ClientStreamingServer[LoadImageRequest, LoadImageResponse]

// Images_ServiceDesc is the grpc.ServiceDesc for Images service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Images_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k3sm.runtime.v1.Images",
	HandlerType: (*ImagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _Images_ListImages_Handler,
		},
		{
			MethodName: "ImageFsInfo",
			Handler:    _Images_ImageFsInfo_Handler,
		},
		{
			MethodName: "RemoveImage",
			Handler:    _Images_RemoveImage_Handler,
		},
		{
			MethodName: "PruneImages",
			Handler:    _Images_PruneImages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoadImage",
			Handler:       _Images_LoadImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "runtime/v1/images.proto",
}
