// Package runtime.v1 is the k3sm node runtime contract: the gRPC API the
// k3sm Virtual Kubelet provider (k3sm.io/k3sm) calls and the native runtime
// daemon (k3sm.io/runtimed) implements. Pods run as native Darwin processes
// (no Linux, no chroot) confined by a per-pod Seatbelt profile — see
// k3sm/docs/DESIGN.md §5a.
//
// Stability contract: field numbers are STABLE and the surface is
// ADDITIVE-ONLY forever. Never renumber or repurpose a field; never reuse a
// reserved number/name. `buf breaking` (WIRE_JSON) enforces this.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: runtime/v1/runtime.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_CreatePod_FullMethodName        = "/k3sm.runtime.v1.Runtime/CreatePod"
	Runtime_DeletePod_FullMethodName        = "/k3sm.runtime.v1.Runtime/DeletePod"
	Runtime_UpdatePod_FullMethodName        = "/k3sm.runtime.v1.Runtime/UpdatePod"
	Runtime_WatchPodStatus_FullMethodName   = "/k3sm.runtime.v1.Runtime/WatchPodStatus"
	Runtime_GetPodStatus_FullMethodName     = "/k3sm.runtime.v1.Runtime/GetPodStatus"
	Runtime_GetLogs_FullMethodName          = "/k3sm.runtime.v1.Runtime/GetLogs"
	Runtime_Exec_FullMethodName             = "/k3sm.runtime.v1.Runtime/Exec"
	Runtime_Attach_FullMethodName           = "/k3sm.runtime.v1.Runtime/Attach"
	Runtime_PortForward_FullMethodName      = "/k3sm.runtime.v1.Runtime/PortForward"
	Runtime_GetRuntimeInfo_FullMethodName   = "/k3sm.runtime.v1.Runtime/GetRuntimeInfo"
	Runtime_ListPodStats_FullMethodName     = "/k3sm.runtime.v1.Runtime/ListPodStats"
	Runtime_RestartContainer_FullMethodName = "/k3sm.runtime.v1.Runtime/RestartContainer"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Runtime is the node-local pod runtime. Every RPC is pod-granular: the unit
// of work is a whole Pod (a "PodBox"), never an individual container, because
// k3sm has no namespaces — a pod is one process group / uid / Seatbelt domain.
//
// RPC numbering note: gRPC method names (not numbers) are the wire identity, so
// there is no numeric range to reserve. The M2 process-split adds resource and
// metrics RPCs to THIS service — append-only; do not remove or rename the
// methods below. M2.2 appends ListPodStats and RestartContainer.
type RuntimeClient interface {
	// CreatePod materializes and starts a PodBox: it creates the per-pod dir,
	// applies the Seatbelt profile, and posix_spawns each container as a native
	// process. Idempotent on pod id (a second call for a live pod is a no-op).
	CreatePod(ctx context.Context, in *CreatePodRequest, opts ...grpc.CallOption) (*CreatePodResponse, error)
	// DeletePod kills the pod's process group (SIGKILL), tears down the PodBox,
	// and forgets it. Idempotent: deleting an unknown pod succeeds.
	DeletePod(ctx context.Context, in *DeletePodRequest, opts ...grpc.CallOption) (*DeletePodResponse, error)
	// UpdatePod applies an in-place spec change to a running pod (e.g. an
	// annotation or, at M2, a resource limit). The runtime decides what is
	// updatable in place vs. requires recreate; non-updatable fields are an error.
	UpdatePod(ctx context.Context, in *UpdatePodRequest, opts ...grpc.CallOption) (*UpdatePodResponse, error)
	// WatchPodStatus is a server stream of PodStatus snapshots. The VK
	// PodNotifier consumes this to drive kubectl Pod state event-driven, with no
	// polling. The server SHOULD emit the current status immediately on subscribe
	// and then on every transition. Watching a single pod (pod_id set) or all
	// pods on the node (pod_id empty) are both valid.
	WatchPodStatus(ctx context.Context, in *WatchPodStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PodStatusEvent], error)
	// GetPodStatus returns a single point-in-time PodStatus (the request/response
	// counterpart to WatchPodStatus, for callers that don't want a stream).
	GetPodStatus(ctx context.Context, in *GetPodStatusRequest, opts ...grpc.CallOption) (*GetPodStatusResponse, error)
	// GetLogs is a server stream of a container's combined stdout/stderr. Honors
	// follow/tail/since like `kubectl logs`.
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Exec runs a command in a container (`kubectl exec`). Bidirectional stream:
	// client sends stdin + a resize channel, server sends stdout/stderr and a
	// final exit code.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error)
	// Attach attaches to a container's running process streams (`kubectl attach`).
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachRequest, AttachResponse], error)
	// PortForward forwards a local stream to a pod port (`kubectl port-forward`).
	// Bidirectional: framed payloads carry the per-connection port + bytes.
	PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PortForwardRequest, PortForwardResponse], error)
	// GetRuntimeInfo returns the daemon's version and health. The M2 process
	// split (provider and runtimed as separate processes) uses this for the
	// version-compat handshake across the IPC boundary.
	GetRuntimeInfo(ctx context.Context, in *GetRuntimeInfoRequest, opts ...grpc.CallOption) (*GetRuntimeInfoResponse, error)
	// ListPodStats returns a resource-usage snapshot for pods on the node — the
	// metrics path behind `kubectl top` / the kubelet Summary API. pod_id empty =
	// all pods on the node; pod_id set = that one pod. runtimed sources each
	// sample from proc_pid_rusage (ri_phys_footprint, NOT RSS); the provider
	// serves the Summary API from them. Added in M2.2 (append-only).
	ListPodStats(ctx context.Context, in *ListPodStatsRequest, opts ...grpc.CallOption) (*ListPodStatsResponse, error)
	// RestartContainer restarts a single container in a running pod in place
	// (terminate its process within the grace window, then re-spawn from the same
	// spec) and increments ContainerStatus.restart_count. A failed liveness probe
	// drives this — it is the runtime action the provider's probe runner invokes
	// (the seam that, pre-M2.2, only bumped restart_count via a nil restartFunc).
	// Added in M2.2 (append-only).
	RestartContainer(ctx context.Context, in *RestartContainerRequest, opts ...grpc.CallOption) (*RestartContainerResponse, error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	return &runtimeClient{cc}
}

func (c *runtimeClient) CreatePod(ctx context.Context, in *CreatePodRequest, opts ...grpc.CallOption) (*CreatePodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePodResponse)
	err := c.cc.Invoke(ctx, Runtime_CreatePod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DeletePod(ctx context.Context, in *DeletePodRequest, opts ...grpc.CallOption) (*DeletePodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePodResponse)
	err := c.cc.Invoke(ctx, Runtime_DeletePod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) UpdatePod(ctx context.Context, in *UpdatePodRequest, opts ...grpc.CallOption) (*UpdatePodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePodResponse)
	err := c.cc.Invoke(ctx, Runtime_UpdatePod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) WatchPodStatus(ctx context.Context, in *WatchPodStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PodStatusEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[0], Runtime_WatchPodStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPodStatusRequest, PodStatusEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_WatchPodStatusClient = grpc.ServerStreamingClient[PodStatusEvent]

func (c *runtimeClient) GetPodStatus(ctx context.Context, in *GetPodStatusRequest, opts ...grpc.CallOption) (*GetPodStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPodStatusResponse)
	err := c.cc.Invoke(ctx, Runtime_GetPodStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[1], Runtime_GetLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_GetLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *runtimeClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[2], Runtime_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_ExecClient = grpc.BidiStreamingClient[ExecRequest, ExecResponse]

func (c *runtimeClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachRequest, AttachResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[3], Runtime_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachRequest, AttachResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_AttachClient = grpc.BidiStreamingClient[AttachRequest, AttachResponse]

func (c *runtimeClient) PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PortForwardRequest, PortForwardResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[4], Runtime_PortForward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PortForwardRequest, PortForwardResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_PortForwardClient = grpc.BidiStreamingClient[PortForwardRequest, PortForwardResponse]

func (c *runtimeClient) GetRuntimeInfo(ctx context.Context, in *GetRuntimeInfoRequest, opts ...grpc.CallOption) (*GetRuntimeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeInfoResponse)
	err := c.cc.Invoke(ctx, Runtime_GetRuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListPodStats(ctx context.Context, in *ListPodStatsRequest, opts ...grpc.CallOption) (*ListPodStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPodStatsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListPodStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RestartContainer(ctx context.Context, in *RestartContainerRequest, opts ...grpc.CallOption) (*RestartContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartContainerResponse)
	err := c.cc.Invoke(ctx, Runtime_RestartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
//
// Runtime is the node-local pod runtime. Every RPC is pod-granular: the unit
// of work is a whole Pod (a "PodBox"), never an individual container, because
// k3sm has no namespaces — a pod is one process group / uid / Seatbelt domain.
//
// RPC numbering note: gRPC method names (not numbers) are the wire identity, so
// there is no numeric range to reserve. The M2 process-split adds resource and
// metrics RPCs to THIS service — append-only; do not remove or rename the
// methods below. M2.2 appends ListPodStats and RestartContainer.
type RuntimeServer interface {
	// CreatePod materializes and starts a PodBox: it creates the per-pod dir,
	// applies the Seatbelt profile, and posix_spawns each container as a native
	// process. Idempotent on pod id (a second call for a live pod is a no-op).
	CreatePod(context.Context, *CreatePodRequest) (*CreatePodResponse, error)
	// DeletePod kills the pod's process group (SIGKILL), tears down the PodBox,
	// and forgets it. Idempotent: deleting an unknown pod succeeds.
	DeletePod(context.Context, *DeletePodRequest) (*DeletePodResponse, error)
	// UpdatePod applies an in-place spec change to a running pod (e.g. an
	// annotation or, at M2, a resource limit). The runtime decides what is
	// updatable in place vs. requires recreate; non-updatable fields are an error.
	UpdatePod(context.Context, *UpdatePodRequest) (*UpdatePodResponse, error)
	// WatchPodStatus is a server stream of PodStatus snapshots. The VK
	// PodNotifier consumes this to drive kubectl Pod state event-driven, with no
	// polling. The server SHOULD emit the current status immediately on subscribe
	// and then on every transition. Watching a single pod (pod_id set) or all
	// pods on the node (pod_id empty) are both valid.
	WatchPodStatus(*WatchPodStatusRequest, grpc.ServerStreamingServer[PodStatusEvent]) error
	// GetPodStatus returns a single point-in-time PodStatus (the request/response
	// counterpart to WatchPodStatus, for callers that don't want a stream).
	GetPodStatus(context.Context, *GetPodStatusRequest) (*GetPodStatusResponse, error)
	// GetLogs is a server stream of a container's combined stdout/stderr. Honors
	// follow/tail/since like `kubectl logs`.
	GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	// Exec runs a command in a container (`kubectl exec`). Bidirectional stream:
	// client sends stdin + a resize channel, server sends stdout/stderr and a
	// final exit code.
	Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error
	// Attach attaches to a container's running process streams (`kubectl attach`).
	Attach(grpc.BidiStreamingServer[AttachRequest, AttachResponse]) error
	// PortForward forwards a local stream to a pod port (`kubectl port-forward`).
	// Bidirectional: framed payloads carry the per-connection port + bytes.
	PortForward(grpc.BidiStreamingServer[PortForwardRequest, PortForwardResponse]) error
	// GetRuntimeInfo returns the daemon's version and health. The M2 process
	// split (provider and runtimed as separate processes) uses this for the
	// version-compat handshake across the IPC boundary.
	GetRuntimeInfo(context.Context, *GetRuntimeInfoRequest) (*GetRuntimeInfoResponse, error)
	// ListPodStats returns a resource-usage snapshot for pods on the node — the
	// metrics path behind `kubectl top` / the kubelet Summary API. pod_id empty =
	// all pods on the node; pod_id set = that one pod. runtimed sources each
	// sample from proc_pid_rusage (ri_phys_footprint, NOT RSS); the provider
	// serves the Summary API from them. Added in M2.2 (append-only).
	ListPodStats(context.Context, *ListPodStatsRequest) (*ListPodStatsResponse, error)
	// RestartContainer restarts a single container in a running pod in place
	// (terminate its process within the grace window, then re-spawn from the same
	// spec) and increments ContainerStatus.restart_count. A failed liveness probe
	// drives this — it is the runtime action the provider's probe runner invokes
	// (the seam that, pre-M2.2, only bumped restart_count via a nil restartFunc).
	// Added in M2.2 (append-only).
	RestartContainer(context.Context, *RestartContainerRequest) (*RestartContainerResponse, error)
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) CreatePod(context.Context, *CreatePodRequest) (*CreatePodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePod not implemented")
}
func (UnimplementedRuntimeServer) DeletePod(context.Context, *DeletePodRequest) (*DeletePodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePod not implemented")
}
func (UnimplementedRuntimeServer) UpdatePod(context.Context, *UpdatePodRequest) (*UpdatePodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePod not implemented")
}
func (UnimplementedRuntimeServer) WatchPodStatus(*WatchPodStatusRequest, grpc.ServerStreamingServer[PodStatusEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchPodStatus not implemented")
}
func (UnimplementedRuntimeServer) GetPodStatus(context.Context, *GetPodStatusRequest) (*GetPodStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodStatus not implemented")
}
func (UnimplementedRuntimeServer) GetLogs(*GetLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedRuntimeServer) Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedRuntimeServer) Attach(grpc.BidiStreamingServer[AttachRequest, AttachResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedRuntimeServer) PortForward(grpc.BidiStreamingServer[PortForwardRequest, PortForwardResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PortForward not implemented")
}
func (UnimplementedRuntimeServer) GetRuntimeInfo(context.Context, *GetRuntimeInfoRequest) (*GetRuntimeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntimeInfo not implemented")
}
func (UnimplementedRuntimeServer) ListPodStats(context.Context, *ListPodStatsRequest) (*ListPodStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPodStats not implemented")
}
func (UnimplementedRuntimeServer) RestartContainer(context.Context, *RestartContainerRequest) (*RestartContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartContainer not implemented")
}
func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {}
func (UnimplementedRuntimeServer) testEmbeddedByValue()                 {}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	// If the following call pancis, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runtime_ServiceDesc, srv)
}

func _Runtime_CreatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CreatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CreatePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CreatePod(ctx, req.(*CreatePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DeletePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DeletePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DeletePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DeletePod(ctx, req.(*DeletePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_UpdatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).UpdatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_UpdatePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).UpdatePod(ctx, req.(*UpdatePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_WatchPodStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPodStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).WatchPodStatus(m, &grpc.GenericServerStream[WatchPodStatusRequest, PodStatusEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_WatchPodStatusServer = grpc.ServerStreamingServer[PodStatusEvent]

func _Runtime_GetPodStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetPodStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetPodStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetPodStatus(ctx, req.(*GetPodStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).GetLogs(m, &grpc.GenericServerStream[GetLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_GetLogsServer = grpc.ServerStreamingServer[LogEntry]

func _Runtime_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServer).Exec(&grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_ExecServer = grpc.BidiStreamingServer[ExecRequest, ExecResponse]

func _Runtime_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServer).Attach(&grpc.GenericServerStream[AttachRequest, AttachResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_AttachServer = grpc.BidiStreamingServer[AttachRequest, AttachResponse]

func _Runtime_PortForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServer).PortForward(&grpc.GenericServerStream[PortForwardRequest, PortForwardResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_PortForwardServer = grpc.BidiStreamingServer[PortForwardRequest, PortForwardResponse]

func _Runtime_GetRuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetRuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetRuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetRuntimeInfo(ctx, req.(*GetRuntimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListPodStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListPodStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListPodStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListPodStats(ctx, req.(*ListPodStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RestartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RestartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RestartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RestartContainer(ctx, req.(*RestartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k3sm.runtime.v1.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePod",
			Handler:    _Runtime_CreatePod_Handler,
		},
		{
			MethodName: "DeletePod",
			Handler:    _Runtime_DeletePod_Handler,
		},
		{
			MethodName: "UpdatePod",
			Handler:    _Runtime_UpdatePod_Handler,
		},
		{
			MethodName: "GetPodStatus",
			Handler:    _Runtime_GetPodStatus_Handler,
		},
		{
			MethodName: "GetRuntimeInfo",
			Handler:    _Runtime_GetRuntimeInfo_Handler,
		},
		{
			MethodName: "ListPodStats",
			Handler:    _Runtime_ListPodStats_Handler,
		},
		{
			MethodName: "RestartContainer",
			Handler:    _Runtime_RestartContainer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPodStatus",
			Handler:       _Runtime_WatchPodStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLogs",
			Handler:       _Runtime_GetLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _Runtime_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Attach",
			Handler:       _Runtime_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PortForward",
			Handler:       _Runtime_PortForward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "runtime/v1/runtime.proto",
}
